use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use hydra_core::name::EnvName;
use hydra_core::paths::HydraPaths;
use hydra_core::secret::{SecretRef, SecretStore, StoreError};
use serde::{Deserialize, Serialize};

/// Names (never values) of stored secrets, because Credential Manager can't be listed through keyring.
#[derive(Default, Serialize, Deserialize)]
struct Index {
    #[serde(default)]
    keys: BTreeMap<String, BTreeSet<String>>,
}

/// Secret values in the OS credential store (Windows Credential Manager), names in `~/.hydra/secrets.toml`.
pub struct KeyringStore {
    service: String,
    index_path: PathBuf,
}

/// Named when a value is rejected as too long; Credential Manager holds at most 2560 bytes of UTF-16.
const TOO_LONG_LIMIT: &str = if cfg!(windows) {
    "Windows Credential Manager (max ~1280 characters)"
} else {
    "the system credential store"
};

fn backend(e: impl std::fmt::Display) -> StoreError {
    StoreError::Backend(e.to_string())
}

impl KeyringStore {
    pub fn new(service: impl Into<String>, index_path: PathBuf) -> Self {
        Self {
            service: service.into(),
            index_path,
        }
    }

    /// Service name from `HYDRA_KEYRING_SERVICE` (tests), default `hydra`.
    pub fn from_env(paths: &HydraPaths) -> Self {
        let service =
            std::env::var("HYDRA_KEYRING_SERVICE").unwrap_or_else(|_| "hydra".to_string());
        Self::new(service, paths.secret_index())
    }

    fn entry(&self, r: &SecretRef) -> Result<keyring::Entry, StoreError> {
        keyring::Entry::new(&self.service, &r.path()).map_err(backend)
    }

    fn read_index(&self) -> Result<Index, StoreError> {
        match std::fs::read_to_string(&self.index_path) {
            Ok(t) => toml::from_str(&t).map_err(backend),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Index::default()),
            Err(e) => Err(backend(e)),
        }
    }

    fn write_index(&self, idx: &Index) -> Result<(), StoreError> {
        if let Some(dir) = self.index_path.parent() {
            std::fs::create_dir_all(dir).map_err(backend)?;
        }
        let body = toml::to_string(idx).map_err(backend)?;
        let text = format!(
            "# generated by hydra: names of stored secrets (values live in the credential store)\n{body}"
        );
        std::fs::write(&self.index_path, text).map_err(backend)
    }
}

impl SecretStore for KeyringStore {
    fn get(&self, r: &SecretRef) -> Result<Option<String>, StoreError> {
        match self.entry(r)?.get_password() {
            Ok(v) => Ok(Some(v)),
            Err(keyring::Error::NoEntry) => Ok(None),
            Err(e) => Err(backend(e)),
        }
    }

    fn set(&self, r: &SecretRef, value: &str) -> Result<(), StoreError> {
        self.entry(r)?.set_password(value).map_err(|e| match e {
            keyring::Error::TooLong(..) => {
                StoreError::Backend(format!("{} is too long for {TOO_LONG_LIMIT}", r.path()))
            }
            e => backend(e),
        })?;
        let mut idx = self.read_index()?;
        idx.keys
            .entry(r.env.to_string())
            .or_default()
            .insert(r.key.clone());
        self.write_index(&idx)
    }

    fn delete(&self, r: &SecretRef) -> Result<bool, StoreError> {
        let deleted = match self.entry(r)?.delete_credential() {
            Ok(()) => true,
            Err(keyring::Error::NoEntry) => false,
            Err(e) => return Err(backend(e)),
        };
        let mut idx = self.read_index()?;
        if let Some(keys) = idx.keys.get_mut(r.env.as_str()) {
            keys.remove(&r.key);
            if keys.is_empty() {
                idx.keys.remove(r.env.as_str());
            }
        }
        self.write_index(&idx)?;
        Ok(deleted)
    }

    fn list(&self, env: &EnvName) -> Result<Vec<String>, StoreError> {
        Ok(self
            .read_index()?
            .keys
            .get(env.as_str())
            .map(|k| k.iter().cloned().collect())
            .unwrap_or_default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_through_credential_manager() {
        let dir = tempfile::tempdir().unwrap();
        let service = format!("hydra-test-{}", std::process::id());
        let store = KeyringStore::new(&service, dir.path().join("secrets.toml"));
        let r = SecretRef::parse_path("work/linear").unwrap();
        let work = EnvName::parse("work").unwrap();

        assert_eq!(store.get(&r).unwrap(), None);
        store.set(&r, "lin_api_value").unwrap();
        assert_eq!(store.get(&r).unwrap().as_deref(), Some("lin_api_value"));
        assert_eq!(store.list(&work).unwrap(), vec!["linear"]);
        let index = std::fs::read_to_string(dir.path().join("secrets.toml")).unwrap();
        assert!(index.contains("linear") && !index.contains("lin_api_value"));

        assert!(store.delete(&r).unwrap());
        assert!(!store.delete(&r).unwrap());
        assert!(store.list(&work).unwrap().is_empty());
    }

    #[test]
    #[cfg(windows)]
    fn values_too_long_for_credential_manager_get_a_clear_error() {
        let dir = tempfile::tempdir().unwrap();
        let service = format!("hydra-test-long-{}", std::process::id());
        let store = KeyringStore::new(&service, dir.path().join("secrets.toml"));
        let r = SecretRef::parse_path("work/huge").unwrap();
        let err = store.set(&r, &"x".repeat(2000)).unwrap_err().to_string();
        assert!(
            err.contains("too long for Windows Credential Manager (max ~1280 characters)"),
            "{err}"
        );
        assert_eq!(store.get(&r).unwrap(), None);
        assert!(!dir.path().join("secrets.toml").exists());
    }
}
