use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellKind {
    Pwsh,
    Bash,
}

impl ShellKind {
    pub fn parse(s: &str) -> Option<Self> {
        match s.to_ascii_lowercase().as_str() {
            "pwsh" | "powershell" => Some(Self::Pwsh),
            "bash" => Some(Self::Bash),
            _ => None,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Pwsh => "pwsh",
            Self::Bash => "bash",
        }
    }
}

pub struct PromptStyle<'a> {
    pub name: &'a str,
    pub rgb: Option<(u8, u8, u8)>,
}

pub fn find_shell(kind: ShellKind, git_bash: Option<&Path>) -> Option<PathBuf> {
    match kind {
        ShellKind::Pwsh => {
            crate::process::find_on_path(if cfg!(windows) { "pwsh.exe" } else { "pwsh" })
        }
        ShellKind::Bash => {
            if let Some(p) = git_bash {
                return p.is_file().then(|| p.to_path_buf());
            }
            if cfg!(windows) {
                let p = PathBuf::from(std::env::var_os("ProgramFiles")?)
                    .join("Git")
                    .join("bin")
                    .join("bash.exe");
                p.is_file().then_some(p)
            } else {
                crate::process::find_on_path("bash")
            }
        }
    }
}

fn header(name: &str) -> String {
    format!(
        "# generated by hydra for environment \"{name}\" - edit ~/.hydra/envs/{name}/env.toml instead\n"
    )
}

/// `C:\a\b` -> `/c/a/b` (Git Bash form).
pub fn to_msys(p: &Path) -> String {
    let s = p.to_string_lossy().replace('\\', "/");
    let b = s.as_bytes();
    if b.len() >= 2 && b[1] == b':' && b[0].is_ascii_alphabetic() {
        format!("/{}{}", (b[0] as char).to_ascii_lowercase(), &s[2..])
    } else {
        s
    }
}

/// POSIX single-quoted string.
pub fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

pub fn render_pwsh_init(style: &PromptStyle, prepend: &[PathBuf]) -> String {
    let mut s = header(style.name);
    // -NoProfile skips all four profiles, so load them here in pwsh's own order. A foreach
    // statement (not ForEach-Object) keeps the dot-sourcing in the caller's scope.
    s.push_str("foreach ($p in $PROFILE.AllUsersAllHosts, $PROFILE.AllUsersCurrentHost, $PROFILE.CurrentUserAllHosts, $PROFILE.CurrentUserCurrentHost) { if ($p -and (Test-Path $p)) { . $p } }\n");
    if !prepend.is_empty() {
        let joined = prepend
            .iter()
            .map(|p| p.to_string_lossy().into_owned())
            .collect::<Vec<_>>()
            .join(";");
        s.push_str(&format!(
            "$env:PATH = '{}' + ';' + $env:PATH\n",
            joined.replace('\'', "''")
        ));
    }
    let tag = match style.rgb {
        Some((r, g, b)) => format!(
            "$([char]27)[38;2;{r};{g};{b}m[{}]$([char]27)[0m ",
            style.name
        ),
        None => format!("[{}] ", style.name),
    };
    s.push_str("$function:__hydra_prompt = $function:prompt\n");
    s.push_str(&format!(
        "function global:prompt {{ \"{tag}\" + (& $function:__hydra_prompt) }}\n"
    ));
    s
}

pub fn render_bash_init(style: &PromptStyle, prepend: &[PathBuf]) -> String {
    let mut s = header(style.name);
    s.push_str("[ -f /etc/profile ] && . /etc/profile\n");
    s.push_str("if [ -f ~/.bash_profile ]; then . ~/.bash_profile; elif [ -f ~/.bashrc ]; then . ~/.bashrc; fi\n");
    if !prepend.is_empty() {
        let joined = prepend
            .iter()
            .map(|p| to_msys(p))
            .collect::<Vec<_>>()
            .join(":");
        s.push_str(&format!("export PATH={}:\"$PATH\"\n", sh_quote(&joined)));
    }
    let tag = match style.rgb {
        Some((r, g, b)) => format!("\\[\\e[38;2;{r};{g};{b}m\\][{}]\\[\\e[0m\\] ", style.name),
        None => format!("[{}] ", style.name),
    };
    s.push_str(&format!("PS1={}\"$PS1\"\n", sh_quote(&tag)));
    s
}

/// Writes `state/<env>/shell/init.ps1` or `init.bash` and returns its path.
pub fn write_init(
    kind: ShellKind,
    state_dir: &Path,
    style: &PromptStyle,
    prepend: &[PathBuf],
) -> std::io::Result<PathBuf> {
    let dir = state_dir.join("shell");
    std::fs::create_dir_all(&dir)?;
    let (file, text) = match kind {
        ShellKind::Pwsh => ("init.ps1", render_pwsh_init(style, prepend)),
        ShellKind::Bash => ("init.bash", render_bash_init(style, prepend)),
    };
    let path = dir.join(file);
    std::fs::write(&path, text)?;
    Ok(path)
}

pub fn shell_command(kind: ShellKind, exe: &Path, init: &Path) -> Command {
    let mut cmd = Command::new(exe);
    match kind {
        ShellKind::Pwsh => {
            cmd.args(["-NoLogo", "-NoProfile", "-NoExit", "-Command"]);
            cmd.arg(format!(
                ". '{}'",
                init.to_string_lossy().replace('\'', "''")
            ));
        }
        ShellKind::Bash => {
            cmd.env("CHERE_INVOKING", "1"); // stops Git Bash's /etc/profile from cd-ing to ~
            cmd.arg("--rcfile").arg(to_msys(init)).arg("-i");
        }
    }
    cmd
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEAL: PromptStyle = PromptStyle {
        name: "work",
        rgb: Some((31, 154, 138)),
    };

    #[test]
    fn pwsh_init() {
        let out = render_pwsh_init(&TEAL, &[PathBuf::from("C:\\h\\tools")]);
        assert_eq!(
            out,
            "# generated by hydra for environment \"work\" - edit ~/.hydra/envs/work/env.toml instead\n\
             foreach ($p in $PROFILE.AllUsersAllHosts, $PROFILE.AllUsersCurrentHost, $PROFILE.CurrentUserAllHosts, $PROFILE.CurrentUserCurrentHost) { if ($p -and (Test-Path $p)) { . $p } }\n\
             $env:PATH = 'C:\\h\\tools' + ';' + $env:PATH\n\
             $function:__hydra_prompt = $function:prompt\n\
             function global:prompt { \"$([char]27)[38;2;31;154;138m[work]$([char]27)[0m \" + (& $function:__hydra_prompt) }\n"
        );
    }

    #[test]
    fn bash_init() {
        let out = render_bash_init(&TEAL, &[PathBuf::from("C:\\h\\tools")]);
        assert_eq!(
            out,
            "# generated by hydra for environment \"work\" - edit ~/.hydra/envs/work/env.toml instead\n\
             [ -f /etc/profile ] && . /etc/profile\n\
             if [ -f ~/.bash_profile ]; then . ~/.bash_profile; elif [ -f ~/.bashrc ]; then . ~/.bashrc; fi\n\
             export PATH='/c/h/tools':\"$PATH\"\n\
             PS1='\\[\\e[38;2;31;154;138m\\][work]\\[\\e[0m\\] '\"$PS1\"\n"
        );
    }

    #[test]
    fn inits_quote_paths_with_spaces() {
        let style = PromptStyle {
            name: "work",
            rgb: None,
        };
        let p = [PathBuf::from("C:\\Users\\Jane O'Doe\\tools")];
        assert!(
            render_pwsh_init(&style, &p)
                .contains("$env:PATH = 'C:\\Users\\Jane O''Doe\\tools' + ';'")
        );
        assert!(
            render_bash_init(&style, &p)
                .contains("export PATH='/c/Users/Jane O'\\''Doe/tools':\"$PATH\"")
        );
        assert!(render_bash_init(&style, &[]).contains("PS1='[work] '\"$PS1\""));
    }

    #[test]
    fn msys_paths() {
        assert_eq!(to_msys(Path::new("C:\\Users\\me")), "/c/Users/me");
        assert_eq!(to_msys(Path::new("relative\\x")), "relative/x");
    }

    #[test]
    fn shell_commands() {
        let init = Path::new("C:\\h\\state\\work\\shell\\init.ps1");
        let cmd = shell_command(ShellKind::Pwsh, Path::new("pwsh.exe"), init);
        let args: Vec<_> = cmd
            .get_args()
            .map(|a| a.to_string_lossy().into_owned())
            .collect();
        assert_eq!(
            args,
            vec![
                "-NoLogo",
                "-NoProfile",
                "-NoExit",
                "-Command",
                ". 'C:\\h\\state\\work\\shell\\init.ps1'"
            ]
        );

        let cmd = shell_command(
            ShellKind::Bash,
            Path::new("bash.exe"),
            Path::new("C:\\h\\init.bash"),
        );
        let args: Vec<_> = cmd
            .get_args()
            .map(|a| a.to_string_lossy().into_owned())
            .collect();
        assert_eq!(args, vec!["--rcfile", "/c/h/init.bash", "-i"]);
        assert!(
            cmd.get_envs()
                .any(|(k, v)| k == "CHERE_INVOKING" && v == Some(std::ffi::OsStr::new("1")))
        );
    }

    #[test]
    fn parses_shell_names() {
        assert_eq!(ShellKind::parse("pwsh"), Some(ShellKind::Pwsh));
        assert_eq!(ShellKind::parse("PowerShell"), Some(ShellKind::Pwsh));
        assert_eq!(ShellKind::parse("bash"), Some(ShellKind::Bash));
        assert_eq!(ShellKind::parse("fish"), None);
    }
}
