use std::path::{Path, PathBuf};

use hydra_core::config::{EnvConfig, load_global};
use hydra_core::contribution::Contribution;
use hydra_core::paths::expand_tilde;
use hydra_core::provider::{CommandRunner, Ctx, IdentityReport, Provider, ProviderError, Status};
use hydra_platform::links::{is_link, link_dir, unlink};

use crate::claude_files::{merge_settings, render_claude_md, sync_mcp};
use crate::report::report;

pub struct Claude;

/// Folders shared from the base into every environment (when they exist there).
pub const SHARED_DIRS: &[&str] = &[
    "skills",
    "commands",
    "agents",
    "hooks",
    "output-styles",
    "plugins",
];

const MANAGED: &[&str] = &[
    "CLAUDE_CONFIG_DIR",
    "ANTHROPIC_API_KEY",
    "ANTHROPIC_AUTH_TOKEN",
    "CLAUDE_CODE_OAUTH_TOKEN",
];

const README: &str = "generated by hydra\r\n\
\r\n\
This folder is Claude Code's config folder for one hydra environment (CLAUDE_CONFIG_DIR).\r\n\
- skills, commands, agents, hooks, output-styles, plugins: links to your shared ~/.claude folders\r\n\
- settings.json and CLAUDE.md: rebuilt on every launch; edit ~/.claude/... or ~/.hydra/envs/<env>/claude/... instead\r\n\
- .claude.json: Claude's own state; hydra only refreshes its mcpServers key from ~/.claude.json\r\n\
- everything else (sign-in, history, projects) belongs to this environment only\r\n";

struct Layout {
    base: PathBuf,
    base_global: PathBuf,
    over: PathBuf,
    dir: PathBuf,
}

fn layout(ctx: &Ctx) -> Result<Layout, ProviderError> {
    let global = load_global(ctx.paths).map_err(|e| ProviderError::new(e.to_string()))?;
    let (base, base_global) = match &global.claude_base {
        Some(b) => {
            let base = expand_tilde(b, ctx.user_home);
            let g = base.join(".claude.json");
            (base, g)
        }
        None => (
            ctx.user_home.join(".claude"),
            ctx.user_home.join(".claude.json"),
        ),
    };
    Ok(Layout {
        base,
        base_global,
        over: ctx.paths.env_dir(ctx.name).join("claude"),
        dir: ctx.provider_dir("claude"),
    })
}

fn read_opt(path: &Path) -> Result<Option<String>, ProviderError> {
    match std::fs::read_to_string(path) {
        Ok(s) => Ok(Some(
            s.strip_prefix('\u{feff}').map(str::to_string).unwrap_or(s),
        )),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(ProviderError::new(format!(
            "can't read {}: {e}",
            path.display()
        ))),
    }
}

/// Writes only when the content changed, via a temp file + rename so Claude never sees half a file.
fn write_if_changed(path: &Path, content: &str) -> Result<(), ProviderError> {
    if read_opt(path)?.as_deref() == Some(content) {
        return Ok(());
    }
    let tmp = path.with_extension("hydra-tmp");
    std::fs::write(&tmp, content)?;
    std::fs::rename(&tmp, path)?;
    Ok(())
}

fn link_shared(l: &Layout, name: &str, env_file: &Path) -> Result<(), ProviderError> {
    let target = [l.over.join(name), l.base.join(name)]
        .into_iter()
        .find(|p| p.is_dir());
    let link = l.dir.join(name);
    if is_link(&link) {
        unlink(&link)?;
    } else if link.is_dir() {
        let empty = std::fs::read_dir(&link)?.next().is_none();
        if !empty {
            return Err(ProviderError::new(format!(
                "{} is a real folder, not a link to your shared ~/.claude/{name}",
                link.display()
            ))
            .with_fix(format!(
                "move anything you want to keep into ~/.claude/{name} (or {}), then delete {}",
                env_file.display(),
                link.display()
            )));
        }
        std::fs::remove_dir(&link)?;
    }
    if let Some(t) = target {
        link_dir(&t, &link)?;
    }
    Ok(())
}

impl Provider for Claude {
    fn id(&self) -> &'static str {
        "claude"
    }
    fn is_configured(&self, env: &EnvConfig) -> bool {
        env.claude.is_some()
    }
    fn managed_vars(&self) -> &'static [&'static str] {
        MANAGED
    }

    fn materialise(&self, ctx: &Ctx) -> Result<(), ProviderError> {
        let l = layout(ctx)?;
        std::fs::create_dir_all(&l.dir)?;
        let exclude = ctx
            .env
            .claude
            .as_ref()
            .map(|c| c.mcp.exclude.clone())
            .unwrap_or_default();
        let over_dir = l.over.clone();
        for name in SHARED_DIRS {
            link_shared(&l, name, &over_dir.join(name))?;
        }
        let settings = merge_settings(
            read_opt(&l.base.join("settings.json"))?.as_deref(),
            read_opt(&l.over.join("settings.json"))?.as_deref(),
            &exclude,
        )
        .map_err(ProviderError::new)?;
        write_if_changed(&l.dir.join("settings.json"), &settings)?;
        let md_path = l.dir.join("CLAUDE.md");
        match render_claude_md(
            ctx.name.as_str(),
            read_opt(&l.base.join("CLAUDE.md"))?.as_deref(),
            read_opt(&l.over.join("CLAUDE.md"))?.as_deref(),
        ) {
            Some(md) => write_if_changed(&md_path, &md)?,
            None => {
                if md_path.is_file() {
                    std::fs::remove_file(&md_path)?;
                }
            }
        }
        let state_path = l.dir.join(".claude.json");
        if let Some(updated) = sync_mcp(
            read_opt(&state_path)?.as_deref(),
            read_opt(&l.base_global)?.as_deref(),
            &exclude,
        )
        .map_err(ProviderError::new)?
        {
            write_if_changed(&state_path, &updated)?;
        }
        write_if_changed(&l.dir.join("README-hydra.txt"), README)?;
        Ok(())
    }

    fn contribute(&self, ctx: &Ctx) -> Result<Contribution, ProviderError> {
        Ok(Contribution::new()
            .path("CLAUDE_CONFIG_DIR", &ctx.provider_dir("claude"))
            .unset("ANTHROPIC_API_KEY")
            .unset("ANTHROPIC_AUTH_TOKEN")
            .unset("CLAUDE_CODE_OAUTH_TOKEN"))
    }

    fn check(&self, ctx: &Ctx, _run: &dyn CommandRunner) -> IdentityReport {
        let dir = ctx.provider_dir("claude");
        if !dir.join(".credentials.json").is_file() {
            return report("claude", Status::Missing, "not signed in");
        }
        let account = std::fs::read_to_string(dir.join(".claude.json"))
            .ok()
            .and_then(|t| serde_json::from_str::<serde_json::Value>(&t).ok())
            .and_then(|v| v.get("oauthAccount").cloned());
        match account
            .as_ref()
            .and_then(|a| a.get("emailAddress"))
            .and_then(|e| e.as_str())
        {
            Some(email) => {
                let org = account
                    .as_ref()
                    .and_then(|a| a.get("organizationName"))
                    .and_then(|o| o.as_str());
                let detail = match org {
                    Some(o) if !o.is_empty() => format!("{email} ({o})"),
                    _ => email.to_string(),
                };
                report("claude", Status::Ok, detail)
            }
            None => report("claude", Status::Info, "signed in"),
        }
    }

    fn auth_command(&self, _ctx: &Ctx) -> Option<Vec<String>> {
        Some(["claude", "auth", "login"].map(String::from).to_vec())
    }

    fn sign_in_hint(&self, ctx: &Ctx) -> Option<String> {
        (!ctx
            .provider_dir("claude")
            .join(".credentials.json")
            .is_file())
        .then(|| "not signed in - run claude auth login".to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::{FakeRunner, Fixture};
    use hydra_core::contribution::VarValue;

    /// A user ~/.claude with a skill, plugins, settings, CLAUDE.md, plus ~/.claude.json.
    fn with_base(f: &Fixture) {
        let base = f.home.join(".claude");
        std::fs::create_dir_all(base.join("skills").join("my-skill")).unwrap();
        std::fs::write(
            base.join("skills").join("my-skill").join("SKILL.md"),
            "skill",
        )
        .unwrap();
        std::fs::create_dir_all(base.join("plugins")).unwrap();
        std::fs::write(base.join("plugins").join("installed_plugins.json"), "{}").unwrap();
        std::fs::write(
            base.join("settings.json"),
            r#"{"model":"opus","mcpServers":{"acme-x":{}}}"#,
        )
        .unwrap();
        std::fs::write(base.join("CLAUDE.md"), "# Base rules").unwrap();
        std::fs::write(base.join(".credentials.json"), "BASE-SECRET").unwrap();
        std::fs::write(f.home.join(".claude.json"), r#"{"mcpServers":{"codegraph":{"command":"cg"},"acme-brain":{}},"oauthAccount":{"emailAddress":"base@x"}}"#).unwrap();
    }

    fn cfg_dir(f: &Fixture) -> PathBuf {
        f.paths.state_dir(&f.name).join("claude")
    }

    #[test]
    fn contributes_config_dir_and_clears_overriding_keys() {
        let f = Fixture::new("[claude]\n");
        let c = Claude.contribute(&f.ctx()).unwrap();
        assert_eq!(
            c.vars["CLAUDE_CONFIG_DIR"],
            VarValue::Literal(cfg_dir(&f).to_string_lossy().into_owned())
        );
        for v in [
            "ANTHROPIC_API_KEY",
            "ANTHROPIC_AUTH_TOKEN",
            "CLAUDE_CODE_OAUTH_TOKEN",
        ] {
            assert!(c.unset.contains(v), "{v}");
        }
        assert!(Claude.is_configured(&f.env));
        assert!(!Claude.is_configured(&Fixture::new("").env));
    }

    #[test]
    fn materialise_shares_the_base_and_keeps_the_sign_in_private() {
        let f = Fixture::new("[claude]\nmcp.exclude = [\"acme*\"]\n");
        with_base(&f);
        Claude.materialise(&f.ctx()).unwrap();
        let dir = cfg_dir(&f);
        assert!(is_link(&dir.join("skills")) && is_link(&dir.join("plugins")));
        assert_eq!(
            std::fs::read_to_string(dir.join("skills").join("my-skill").join("SKILL.md")).unwrap(),
            "skill"
        );
        assert!(
            !dir.join("commands").exists(),
            "only folders that exist in the base are linked"
        );
        assert!(
            !dir.join(".credentials.json").exists(),
            "the base sign-in is never copied"
        );
        let settings: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join("settings.json")).unwrap())
                .unwrap();
        assert_eq!(settings["model"], "opus");
        assert!(settings["mcpServers"].get("acme-x").is_none());
        assert!(
            std::fs::read_to_string(dir.join("CLAUDE.md"))
                .unwrap()
                .contains("# Base rules")
        );
        let state: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join(".claude.json")).unwrap())
                .unwrap();
        assert_eq!(
            state["mcpServers"],
            serde_json::json!({"codegraph": {"command": "cg"}})
        );
        assert!(
            state.get("oauthAccount").is_none(),
            "the base account is never copied"
        );
        assert!(dir.join("README-hydra.txt").is_file());
    }

    #[test]
    fn environment_overrides_win() {
        let f = Fixture::new("[claude]\n");
        with_base(&f);
        let over = f.paths.env_dir(&f.name).join("claude");
        std::fs::create_dir_all(over.join("skills").join("work-skill")).unwrap();
        std::fs::write(over.join("settings.json"), r#"{"model":"sonnet"}"#).unwrap();
        std::fs::write(over.join("CLAUDE.md"), "# Work only").unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        let dir = cfg_dir(&f);
        assert!(dir.join("skills").join("work-skill").is_dir());
        assert!(!dir.join("skills").join("my-skill").exists());
        assert!(
            std::fs::read_to_string(dir.join("settings.json"))
                .unwrap()
                .contains("\"sonnet\"")
        );
        let md = std::fs::read_to_string(dir.join("CLAUDE.md")).unwrap();
        assert!(md.contains("# Base rules") && md.contains("# Work only"));
    }

    #[test]
    fn materialise_is_repeatable_and_follows_base_changes() {
        let f = Fixture::new("[claude]\n");
        with_base(&f);
        Claude.materialise(&f.ctx()).unwrap();
        std::fs::create_dir_all(f.home.join(".claude").join("commands")).unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        assert!(is_link(&cfg_dir(&f).join("commands")));
    }

    #[test]
    fn real_folder_in_place_of_link_is_never_deleted() {
        let f = Fixture::new("[claude]\n");
        with_base(&f);
        let dir = cfg_dir(&f);
        std::fs::create_dir_all(dir.join("plugins")).unwrap();
        std::fs::write(dir.join("plugins").join("mine.json"), "x").unwrap();
        std::fs::create_dir_all(dir.join("skills")).unwrap(); // empty: replaced by the link
        let e = Claude.materialise(&f.ctx()).unwrap_err();
        assert!(
            e.message.contains("plugins") && e.message.contains("real folder"),
            "{}",
            e.message
        );
        assert!(e.fix.is_some());
        assert_eq!(
            std::fs::read_to_string(dir.join("plugins").join("mine.json")).unwrap(),
            "x"
        );
    }

    #[test]
    fn works_without_a_base() {
        let f = Fixture::new("[claude]\n");
        Claude.materialise(&f.ctx()).unwrap();
        let dir = cfg_dir(&f);
        assert!(dir.is_dir());
        assert_eq!(
            std::fs::read_to_string(dir.join("settings.json")).unwrap(),
            "{}\n"
        );
        assert!(!dir.join("CLAUDE.md").exists());
    }

    #[test]
    fn claude_base_setting_moves_the_base() {
        let f = Fixture::new("[claude]\n");
        let alt = f.home.join("dotfiles").join("claude");
        std::fs::create_dir_all(alt.join("skills")).unwrap();
        std::fs::write(alt.join(".claude.json"), r#"{"mcpServers":{"alt":{}}}"#).unwrap();
        std::fs::create_dir_all(f.paths.root()).unwrap();
        let alt_toml = alt.to_string_lossy().replace('\\', "/");
        std::fs::write(
            f.paths.config_file(),
            format!("claude_base = \"{alt_toml}\"\n"),
        )
        .unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        assert!(is_link(&cfg_dir(&f).join("skills")));
        assert!(
            std::fs::read_to_string(cfg_dir(&f).join(".claude.json"))
                .unwrap()
                .contains("\"alt\"")
        );
    }

    #[test]
    fn sign_in_hint_and_identity_come_from_files() {
        let f = Fixture::new("[claude]\n");
        Claude.materialise(&f.ctx()).unwrap();
        assert_eq!(
            Claude.sign_in_hint(&f.ctx()).as_deref(),
            Some("not signed in - run claude auth login")
        );
        let r = Claude.check(&f.ctx(), &FakeRunner::default());
        assert_eq!(r.status, Status::Missing);

        let dir = cfg_dir(&f);
        std::fs::write(dir.join(".credentials.json"), "{}").unwrap();
        std::fs::write(
            dir.join(".claude.json"),
            r#"{"oauthAccount":{"emailAddress":"work@example.com","organizationName":"acme"}}"#,
        )
        .unwrap();
        assert_eq!(Claude.sign_in_hint(&f.ctx()), None);
        let r = Claude.check(&f.ctx(), &FakeRunner::default());
        assert_eq!(
            (r.status, r.detail.as_str()),
            (Status::Ok, "work@example.com (acme)")
        );
        assert_eq!(
            Claude.auth_command(&f.ctx()).unwrap(),
            vec!["claude", "auth", "login"]
        );
    }
}
