use std::path::{Path, PathBuf};

use hydra_core::config::{EnvConfig, load_global};
use hydra_core::contribution::Contribution;
use hydra_core::paths::expand_tilde;
use hydra_core::provider::{CommandRunner, Ctx, IdentityReport, Provider, ProviderError, Status};
use hydra_platform::links::{is_link, link_dir, points_at, unlink};

use crate::claude_files::{add_guard_hook, merge_settings, render_claude_md, sync_mcp};
use crate::report::report;

pub struct Claude;

/// Folders shared from the base into every environment (when they exist there).
pub const SHARED_DIRS: &[&str] = &[
    "skills",
    "commands",
    "agents",
    "hooks",
    "output-styles",
    "plugins",
];

const MANAGED: &[&str] = &[
    "CLAUDE_CONFIG_DIR",
    "ANTHROPIC_API_KEY",
    "ANTHROPIC_AUTH_TOKEN",
    "CLAUDE_CODE_OAUTH_TOKEN",
    "ANTHROPIC_BASE_URL",
    "CLAUDE_CODE_USE_BEDROCK",
    "CLAUDE_CODE_USE_VERTEX",
];

const README: &str = "generated by hydra\r\n\
\r\n\
This folder is Claude Code's config folder for one hydra environment (CLAUDE_CONFIG_DIR).\r\n\
- skills, commands, agents, hooks, output-styles, plugins: links to your shared ~/.claude folders\r\n\
- settings.json and CLAUDE.md: rebuilt on every launch; edit ~/.claude/... or ~/.hydra/envs/<env>/claude/... instead\r\n\
- .claude.json: Claude's own state; hydra only refreshes its mcpServers key from ~/.claude.json\r\n\
- everything else (sign-in, history, projects) belongs to this environment only\r\n";

struct Layout {
    base: PathBuf,
    base_global: PathBuf,
    over: PathBuf,
    dir: PathBuf,
    /// True when the base comes from `claude_base` in config.toml (it must then exist).
    configured_base: bool,
}

fn layout(ctx: &Ctx) -> Result<Layout, ProviderError> {
    let global = load_global(ctx.paths).map_err(|e| ProviderError::new(e.to_string()))?;
    let (base, base_global) = match &global.claude_base {
        Some(b) => {
            let base = expand_tilde(b, ctx.user_home);
            let g = base.join(".claude.json");
            (base, g)
        }
        None => (
            ctx.user_home.join(".claude"),
            ctx.user_home.join(".claude.json"),
        ),
    };
    Ok(Layout {
        base,
        base_global,
        configured_base: global.claude_base.is_some(),
        over: ctx.paths.env_dir(ctx.tool_owner("claude")).join("claude"),
        dir: ctx.provider_dir("claude"),
    })
}

fn read_opt(path: &Path) -> Result<Option<String>, ProviderError> {
    match std::fs::read_to_string(path) {
        Ok(s) => Ok(Some(
            s.strip_prefix('\u{feff}').map(str::to_string).unwrap_or(s),
        )),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(ProviderError::new(format!(
            "can't read {}: {e}",
            path.display()
        ))),
    }
}

/// How often a step that can race with another launch of the same environment is tried.
const ATTEMPTS: u32 = 8;

/// Runs `step` until it succeeds, pausing briefly between tries, so two launches of one
/// environment at the same moment both end up with the same, complete result.
fn with_retries<T>(mut step: impl FnMut() -> Result<T, ProviderError>) -> Result<T, ProviderError> {
    let mut tries = 1;
    loop {
        match step() {
            Ok(v) => return Ok(v),
            Err(e) if tries >= ATTEMPTS => return Err(e),
            Err(_) => {
                std::thread::sleep(std::time::Duration::from_millis(5 * u64::from(tries)));
                tries += 1;
            }
        }
    }
}

/// Writes only when the content changed, via a temp file + rename so Claude never sees half a file.
fn write_if_changed(path: &Path, content: &str) -> Result<(), ProviderError> {
    static SEQ: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
    with_retries(|| {
        if read_opt(path)?.as_deref() == Some(content) {
            return Ok(());
        }
        let seq = SEQ.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let mut tmp = path.as_os_str().to_owned();
        tmp.push(format!(".hydra-tmp-{}-{seq}", std::process::id()));
        let tmp = PathBuf::from(tmp);
        let written = std::fs::write(&tmp, content).and_then(|()| std::fs::rename(&tmp, path));
        if let Err(e) = written {
            let _ = std::fs::remove_file(&tmp);
            return Err(ProviderError::new(format!(
                "can't write {}: {e}",
                path.display()
            )));
        }
        Ok(())
    })
}

fn remove_if_present(path: &Path) -> Result<(), ProviderError> {
    match std::fs::remove_file(path) {
        Err(e) if e.kind() != std::io::ErrorKind::NotFound => Err(ProviderError::new(format!(
            "can't remove {}: {e}",
            path.display()
        ))),
        _ => Ok(()),
    }
}

/// Writes (or, for `None`, removes) a file hydra generates in the config folder, keeping a
/// copy in `.hydra/last/`. If the file was changed since hydra last wrote it (by Claude or
/// by hand), the changed version is first saved as `<file>.bak`; the returned warning says so.
fn write_generated(
    l: &Layout,
    env: &str,
    file: &str,
    content: Option<&str>,
) -> Result<Option<String>, ProviderError> {
    let path = l.dir.join(file);
    let last = l.dir.join(".hydra").join("last").join(file);
    let current = read_opt(&path)?;
    let mut warning = None;
    if let Some(cur) = &current
        && Some(cur.as_str()) != content
        && let Some(prev) = read_opt(&last)?
        && *cur != prev
    {
        let mut bak = path.as_os_str().to_owned();
        bak.push(".bak");
        let bak = PathBuf::from(bak);
        std::fs::copy(&path, &bak).map_err(|e| {
            ProviderError::new(format!(
                "can't save {} as {}: {e}",
                path.display(),
                bak.display()
            ))
        })?;
        warning = Some(format!(
            "hydra: claude: {file} was changed inside {env}; saved your version as {} - put lasting changes in {} or {}",
            bak.display(),
            l.base.join(file).display(),
            l.over.join(file).display()
        ));
    }
    match content {
        Some(c) => {
            write_if_changed(&path, c)?;
            std::fs::create_dir_all(last.parent().expect("has a parent"))?;
            write_if_changed(&last, c)?;
        }
        None => {
            if current.is_some() {
                remove_if_present(&path)?;
            }
            remove_if_present(&last)?;
        }
    }
    Ok(warning)
}

/// Makes `<dir>/<name>` a link to the environment's or the base's `<name>` folder (or
/// removes a stale link when neither exists). Leaves a correct link alone.
fn link_shared(l: &Layout, name: &str, override_dir: &Path) -> Result<(), ProviderError> {
    let target = [override_dir.to_path_buf(), l.base.join(name)]
        .into_iter()
        .find(|p| p.is_dir());
    let link = l.dir.join(name);
    with_retries(|| {
        let done = match &target {
            Some(t) => points_at(&link, t),
            None => std::fs::symlink_metadata(&link).is_err(),
        };
        if done {
            return Ok(());
        }
        if is_link(&link) {
            // Another launch may remove it first; only a link that's still there is an error.
            if let Err(e) = unlink(&link)
                && is_link(&link)
            {
                return Err(e.into());
            }
        } else if link.is_dir() {
            if std::fs::read_dir(&link)?.next().is_some() {
                let shared = l.base.join(name);
                return Err(ProviderError::new(format!(
                    "{} is a real folder, not a link to your shared {}",
                    link.display(),
                    shared.display()
                ))
                .with_fix(format!(
                    "move anything you want to keep into {} (or {}), then delete {}",
                    shared.display(),
                    override_dir.display(),
                    link.display()
                )));
            }
            if let Err(e) = std::fs::remove_dir(&link)
                && e.kind() != std::io::ErrorKind::NotFound
            {
                return Err(e.into());
            }
        } else if target.is_some() && std::fs::symlink_metadata(&link).is_ok() {
            return Err(ProviderError::new(format!(
                "{} is in the way of the link to your shared {name} folder",
                link.display()
            ))
            .with_fix(format!(
                "delete {}; hydra recreates it as a link",
                link.display()
            )));
        }
        if let Some(t) = &target
            && let Err(e) = link_dir(t, &link)
            && !points_at(&link, t)
        {
            // AlreadyExists is fine when another launch made the same link meanwhile.
            return Err(ProviderError::new(format!(
                "can't link {} to {}: {e}",
                link.display(),
                t.display()
            )));
        }
        let ok = match &target {
            Some(t) => points_at(&link, t),
            None => true,
        };
        if ok {
            Ok(())
        } else {
            Err(ProviderError::new(format!(
                "{} changed while hydra was linking it",
                link.display()
            )))
        }
    })
}

/// The `[env]` variable (as written there) that signs Claude in with a key or token instead
/// of the environment's own sign-in, if any.
fn api_key_var(env: &EnvConfig) -> Option<&str> {
    const KEY_VARS: &[&str] = &[
        "ANTHROPIC_API_KEY",
        "ANTHROPIC_AUTH_TOKEN",
        "CLAUDE_CODE_OAUTH_TOKEN",
    ];
    env.env
        .keys()
        .find(|k| KEY_VARS.iter().any(|v| k.eq_ignore_ascii_case(v)))
        .map(String::as_str)
}

/// Refuses to write when the state folder itself has been replaced by a link: hydra would
/// otherwise write (and later delete) files wherever that link points.
fn refuse_linked(path: &Path) -> Result<(), ProviderError> {
    if is_link(path) {
        return Err(ProviderError::new(format!(
            "{} is a link; hydra won't write its files through it",
            path.display()
        ))
        .with_fix(format!(
            "remove the link {} (only the link, e.g. rmdir); hydra recreates it as a folder",
            path.display()
        )));
    }
    Ok(())
}

impl Provider for Claude {
    fn id(&self) -> &'static str {
        "claude"
    }
    fn is_configured(&self, env: &EnvConfig) -> bool {
        env.claude.is_some()
    }
    fn managed_vars(&self) -> &'static [&'static str] {
        MANAGED
    }

    fn materialise(&self, ctx: &Ctx) -> Result<(), ProviderError> {
        let l = layout(ctx)?;
        if l.configured_base && !l.base.is_dir() {
            return Err(ProviderError::new(format!(
                "claude_base {} doesn't exist",
                l.base.display()
            ))
            .with_fix("fix claude_base in config.toml"));
        }
        refuse_linked(&ctx.paths.state_dir(ctx.tool_owner("claude")))?;
        refuse_linked(&l.dir)?;
        std::fs::create_dir_all(&l.dir)?;
        let exclude = ctx
            .env
            .claude
            .as_ref()
            .map(|c| c.mcp.exclude.clone())
            .unwrap_or_default();
        for name in SHARED_DIRS {
            link_shared(&l, name, &l.over.join(name))?;
        }
        let (base_settings, over_settings) =
            (l.base.join("settings.json"), l.over.join("settings.json"));
        let merged = merge_settings(
            read_opt(&base_settings)?
                .as_deref()
                .map(|t| (base_settings.as_path(), t)),
            read_opt(&over_settings)?
                .as_deref()
                .map(|t| (over_settings.as_path(), t)),
            &exclude,
        )
        .map_err(ProviderError::new)?;
        if !merged.dropped.is_empty() {
            warn(&format!(
                "hydra: claude: ignored {} from your shared settings.json (they would give every environment the same sign-in); set them in {} if one environment needs them",
                merged.dropped.join(", "),
                over_settings.display()
            ));
        }
        let settings = with_guard_hook(merged.text);
        let env = ctx.tool_owner("claude").as_str();
        let md = render_claude_md(
            env,
            read_opt(&l.base.join("CLAUDE.md"))?.as_deref(),
            read_opt(&l.over.join("CLAUDE.md"))?.as_deref(),
        );
        for (file, content) in [("settings.json", Some(settings)), ("CLAUDE.md", md)] {
            if let Some(warning) = write_generated(&l, env, file, content.as_deref())? {
                warn(&warning);
            }
        }
        let state_path = l.dir.join(".claude.json");
        if let Some(updated) = sync_mcp(
            read_opt(&state_path)?
                .as_deref()
                .map(|t| (state_path.as_path(), t)),
            read_opt(&l.base_global)?
                .as_deref()
                .map(|t| (l.base_global.as_path(), t)),
            &exclude,
        )
        .map_err(ProviderError::new)?
        {
            write_if_changed(&state_path, &updated)?;
        }
        write_if_changed(&l.dir.join("README-hydra.txt"), README)?;
        Ok(())
    }

    fn contribute(&self, ctx: &Ctx) -> Result<Contribution, ProviderError> {
        let c = Contribution::new().path("CLAUDE_CONFIG_DIR", &ctx.provider_dir("claude"));
        Ok(MANAGED
            .iter()
            .filter(|v| **v != "CLAUDE_CONFIG_DIR")
            .fold(c, |c, v| c.unset(v)))
    }

    fn check(&self, ctx: &Ctx, _run: &dyn CommandRunner) -> IdentityReport {
        if let Some(var) = api_key_var(ctx.env) {
            return report("claude", Status::Info, format!("uses {var} from [env]"));
        }
        let dir = ctx.provider_dir("claude");
        if !dir.join(".credentials.json").is_file() {
            return report("claude", Status::Missing, "not signed in");
        }
        let account = std::fs::read_to_string(dir.join(".claude.json"))
            .ok()
            .and_then(|t| serde_json::from_str::<serde_json::Value>(&t).ok())
            .and_then(|v| v.get("oauthAccount").cloned());
        match account
            .as_ref()
            .and_then(|a| a.get("emailAddress"))
            .and_then(|e| e.as_str())
        {
            Some(email) => {
                let org = account
                    .as_ref()
                    .and_then(|a| a.get("organizationName"))
                    .and_then(|o| o.as_str());
                let detail = match org {
                    Some(o) if !o.is_empty() => format!("{email} ({o})"),
                    _ => email.to_string(),
                };
                report("claude", Status::Ok, detail)
            }
            None => report("claude", Status::Info, "signed in"),
        }
    }

    fn auth_command(&self, _ctx: &Ctx) -> Option<Vec<String>> {
        Some(["claude", "auth", "login"].map(String::from).to_vec())
    }

    fn sign_in_hint(&self, ctx: &Ctx) -> Option<String> {
        if api_key_var(ctx.env).is_some() {
            return None;
        }
        (!ctx
            .provider_dir("claude")
            .join(".credentials.json")
            .is_file())
        .then(|| "not signed in - run claude auth login".to_string())
    }
}

/// Adds hydra's PreToolUse guard hook to the generated settings. Skipped with a warning when
/// hydra's own path is unknown or the settings can't take it.
fn with_guard_hook(text: String) -> String {
    let exe = match std::env::current_exe() {
        Ok(e) => e.to_string_lossy().replace('\\', "/"),
        Err(e) => {
            warn(&format!(
                "hydra: claude: guard hook not added (can't find hydra's own path: {e})"
            ));
            return text;
        }
    };
    match add_guard_hook(&text, &format!("\"{exe}\" guard claude")) {
        Ok(with_hook) => with_hook,
        Err(e) => {
            warn(&format!("hydra: claude: guard hook not added ({e})"));
            text
        }
    }
}

/// Prints a warning to stderr in yellow (plain when stderr isn't a terminal).
fn warn(text: &str) {
    let style = anstyle::Style::new().fg_color(Some(anstyle::AnsiColor::Yellow.into()));
    anstream::eprintln!("{style}{text}{style:#}");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::{FakeRunner, Fixture};
    use hydra_core::contribution::VarValue;

    /// A user ~/.claude with a skill, plugins, settings, CLAUDE.md, plus ~/.claude.json.
    fn with_base(f: &Fixture) {
        let base = f.home.join(".claude");
        std::fs::create_dir_all(base.join("skills").join("my-skill")).unwrap();
        std::fs::write(
            base.join("skills").join("my-skill").join("SKILL.md"),
            "skill",
        )
        .unwrap();
        std::fs::create_dir_all(base.join("plugins")).unwrap();
        std::fs::write(base.join("plugins").join("installed_plugins.json"), "{}").unwrap();
        std::fs::write(
            base.join("settings.json"),
            r#"{"model":"opus","mcpServers":{"acme-x":{}}}"#,
        )
        .unwrap();
        std::fs::write(base.join("CLAUDE.md"), "# Base rules").unwrap();
        std::fs::write(base.join(".credentials.json"), "BASE-SECRET").unwrap();
        std::fs::write(f.home.join(".claude.json"), r#"{"mcpServers":{"codegraph":{"command":"cg"},"acme-brain":{}},"oauthAccount":{"emailAddress":"base@x"}}"#).unwrap();
    }

    fn cfg_dir(f: &Fixture) -> PathBuf {
        f.paths.state_dir(&f.name).join("claude")
    }

    #[test]
    fn contributes_config_dir_and_clears_overriding_keys() {
        let f = Fixture::new("[claude]\n");
        let c = Claude.contribute(&f.ctx()).unwrap();
        assert_eq!(
            c.vars["CLAUDE_CONFIG_DIR"],
            VarValue::Literal(cfg_dir(&f).to_string_lossy().into_owned())
        );
        for v in [
            "ANTHROPIC_API_KEY",
            "ANTHROPIC_AUTH_TOKEN",
            "CLAUDE_CODE_OAUTH_TOKEN",
            "ANTHROPIC_BASE_URL",
            "CLAUDE_CODE_USE_BEDROCK",
            "CLAUDE_CODE_USE_VERTEX",
        ] {
            assert!(c.unset.contains(v), "{v}");
            assert!(Claude.managed_vars().contains(&v), "{v}");
        }
        assert!(Claude.is_configured(&f.env));
        assert!(!Claude.is_configured(&Fixture::new("").env));
    }

    #[test]
    fn borrowed_claude_prepares_the_owners_folder_as_the_owner() {
        let mut f = Fixture::new(
            "[claude]
",
        );
        with_base(&f);
        let personal = hydra_core::name::EnvName::parse("personal").unwrap();
        f.env.borrowed.insert("claude".into(), personal.clone());
        Claude.materialise(&f.ctx()).unwrap();
        let dir = f.paths.state_dir(&personal).join("claude");
        assert!(dir.join("settings.json").is_file());
        assert!(!f.paths.state_dir(&f.name).join("claude").exists());
        // Generated files name the owner, so owner and borrower launches write the same thing.
        if let Ok(md) = std::fs::read_to_string(dir.join("CLAUDE.md")) {
            assert!(!md.contains("work"), "{md}");
        }
    }

    #[test]
    fn materialise_shares_the_base_and_keeps_the_sign_in_private() {
        let f = Fixture::new("[claude]\nmcp.exclude = [\"acme*\"]\n");
        with_base(&f);
        Claude.materialise(&f.ctx()).unwrap();
        let dir = cfg_dir(&f);
        assert!(is_link(&dir.join("skills")) && is_link(&dir.join("plugins")));
        assert_eq!(
            std::fs::read_to_string(dir.join("skills").join("my-skill").join("SKILL.md")).unwrap(),
            "skill"
        );
        assert!(
            !dir.join("commands").exists(),
            "only folders that exist in the base are linked"
        );
        assert!(
            !dir.join(".credentials.json").exists(),
            "the base sign-in is never copied"
        );
        let settings: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join("settings.json")).unwrap())
                .unwrap();
        assert_eq!(settings["model"], "opus");
        assert!(settings["mcpServers"].get("acme-x").is_none());
        assert!(
            std::fs::read_to_string(dir.join("CLAUDE.md"))
                .unwrap()
                .contains("# Base rules")
        );
        let state: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join(".claude.json")).unwrap())
                .unwrap();
        assert_eq!(
            state["mcpServers"],
            serde_json::json!({"codegraph": {"command": "cg"}})
        );
        assert!(
            state.get("oauthAccount").is_none(),
            "the base account is never copied"
        );
        assert!(dir.join("README-hydra.txt").is_file());
    }

    #[test]
    fn environment_overrides_win() {
        let f = Fixture::new("[claude]\n");
        with_base(&f);
        let over = f.paths.env_dir(&f.name).join("claude");
        std::fs::create_dir_all(over.join("skills").join("work-skill")).unwrap();
        std::fs::write(over.join("settings.json"), r#"{"model":"sonnet"}"#).unwrap();
        std::fs::write(over.join("CLAUDE.md"), "# Work only").unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        let dir = cfg_dir(&f);
        assert!(dir.join("skills").join("work-skill").is_dir());
        assert!(!dir.join("skills").join("my-skill").exists());
        assert!(
            std::fs::read_to_string(dir.join("settings.json"))
                .unwrap()
                .contains("\"sonnet\"")
        );
        let md = std::fs::read_to_string(dir.join("CLAUDE.md")).unwrap();
        assert!(md.contains("# Base rules") && md.contains("# Work only"));
    }

    #[test]
    fn a_borrower_uses_the_owners_overrides_not_its_own() {
        let mut f = Fixture::new("[claude]\n");
        with_base(&f);
        let personal = hydra_core::name::EnvName::parse("personal").unwrap();
        f.env.borrowed.insert("claude".into(), personal.clone());
        // The borrower's own override folder is ignored...
        let own = f.paths.env_dir(&f.name).join("claude");
        std::fs::create_dir_all(own.join("skills").join("work-skill")).unwrap();
        std::fs::write(own.join("settings.json"), r#"{"model":"sonnet"}"#).unwrap();
        std::fs::write(own.join("CLAUDE.md"), "# Work only").unwrap();
        // ...in favour of the owner's.
        let owners = f.paths.env_dir(&personal).join("claude");
        std::fs::create_dir_all(owners.join("skills").join("personal-skill")).unwrap();
        std::fs::write(owners.join("settings.json"), r#"{"model":"haiku"}"#).unwrap();
        std::fs::write(owners.join("CLAUDE.md"), "# Personal only").unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        let dir = f.paths.state_dir(&personal).join("claude");
        assert!(dir.join("skills").join("personal-skill").is_dir());
        assert!(!dir.join("skills").join("work-skill").exists());
        let settings = std::fs::read_to_string(dir.join("settings.json")).unwrap();
        assert!(settings.contains("\"haiku\"") && !settings.contains("\"sonnet\""));
        let md = std::fs::read_to_string(dir.join("CLAUDE.md")).unwrap();
        assert!(
            md.contains("# Personal only") && !md.contains("# Work only"),
            "{md}"
        );
    }

    #[test]
    fn materialise_is_repeatable_and_follows_base_changes() {
        let f = Fixture::new("[claude]\n");
        with_base(&f);
        Claude.materialise(&f.ctx()).unwrap();
        std::fs::create_dir_all(f.home.join(".claude").join("commands")).unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        assert!(is_link(&cfg_dir(&f).join("commands")));
    }

    #[test]
    fn concurrent_launches_of_one_environment_all_succeed() {
        for round in 0..20 {
            let f = Fixture::new("[claude]\n");
            with_base(&f);
            std::fs::create_dir_all(f.home.join(".claude").join("commands")).unwrap();
            std::thread::scope(|s| {
                let handles: Vec<_> = (0..4)
                    .map(|_| s.spawn(|| Claude.materialise(&f.ctx())))
                    .collect();
                for h in handles {
                    h.join()
                        .unwrap()
                        .unwrap_or_else(|e| panic!("round {round}: {e}"));
                }
            });
            let dir = cfg_dir(&f);
            assert!(is_link(&dir.join("skills")) && is_link(&dir.join("commands")));
            assert_eq!(
                std::fs::read_to_string(dir.join("skills").join("my-skill").join("SKILL.md"))
                    .unwrap(),
                "skill"
            );
            let leftovers: Vec<_> = std::fs::read_dir(&dir)
                .unwrap()
                .filter_map(|e| e.ok())
                .filter(|e| e.file_name().to_string_lossy().contains("hydra-tmp"))
                .collect();
            assert!(leftovers.is_empty(), "round {round}: {leftovers:?}");
        }
    }

    #[test]
    fn links_that_already_point_right_are_left_alone() {
        let f = Fixture::new("[claude]\n");
        with_base(&f);
        Claude.materialise(&f.ctx()).unwrap();
        let link = cfg_dir(&f).join("skills");
        let created = std::fs::symlink_metadata(&link).unwrap().created().unwrap();
        std::thread::sleep(std::time::Duration::from_millis(50));
        Claude.materialise(&f.ctx()).unwrap();
        assert_eq!(
            std::fs::symlink_metadata(&link).unwrap().created().unwrap(),
            created,
            "the link was recreated"
        );
    }

    #[test]
    fn a_link_to_the_wrong_place_is_repointed() {
        let f = Fixture::new("[claude]\n");
        with_base(&f);
        let dir = cfg_dir(&f);
        let elsewhere = f.home.join("elsewhere");
        std::fs::create_dir_all(&elsewhere).unwrap();
        std::fs::write(elsewhere.join("keep.txt"), "keep").unwrap();
        std::fs::create_dir_all(&dir).unwrap();
        link_dir(&elsewhere, &dir.join("skills")).unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        assert!(dir.join("skills").join("my-skill").is_dir());
        assert_eq!(
            std::fs::read_to_string(elsewhere.join("keep.txt")).unwrap(),
            "keep"
        );
    }

    #[test]
    fn a_plain_file_where_a_link_goes_is_an_error() {
        let f = Fixture::new("[claude]\n");
        with_base(&f);
        let dir = cfg_dir(&f);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("skills"), "mine").unwrap();
        let e = Claude.materialise(&f.ctx()).unwrap_err();
        let path = dir.join("skills").display().to_string();
        assert!(e.message.contains(&path), "{}", e.message);
        assert_eq!(
            e.fix.as_deref(),
            Some(format!("delete {path}; hydra recreates it as a link").as_str())
        );
        assert_eq!(std::fs::read_to_string(dir.join("skills")).unwrap(), "mine");
    }

    #[test]
    fn refuses_to_write_through_a_linked_state_folder() {
        for linked in ["env", "claude"] {
            let f = Fixture::new("[claude]\n");
            with_base(&f);
            let elsewhere = f.home.join("elsewhere");
            std::fs::create_dir_all(&elsewhere).unwrap();
            let state = f.paths.state_dir(&f.name);
            let link = if linked == "env" {
                std::fs::create_dir_all(state.parent().unwrap()).unwrap();
                state.clone()
            } else {
                std::fs::create_dir_all(&state).unwrap();
                state.join("claude")
            };
            link_dir(&elsewhere, &link).unwrap();
            let e = Claude.materialise(&f.ctx()).unwrap_err();
            assert!(
                e.message.contains(&link.display().to_string()) && e.message.contains("link"),
                "{}",
                e.message
            );
            assert!(e.fix.is_some());
            assert_eq!(
                std::fs::read_dir(&elsewhere).unwrap().count(),
                0,
                "{linked}: wrote through the link"
            );
        }
    }

    #[test]
    fn materialised_settings_carry_the_guard_hook() {
        let f = Fixture::new("[claude]\n");
        Claude.materialise(&f.ctx()).unwrap();
        let text = std::fs::read_to_string(cfg_dir(&f).join("settings.json")).unwrap();
        assert!(text.contains("guard claude"), "{text}");
        assert!(text.contains("PreToolUse"), "{text}");
        // Stable across launches: the second materialise changes nothing and makes no .bak.
        Claude.materialise(&f.ctx()).unwrap();
        assert!(!cfg_dir(&f).join("settings.json.bak").exists());
    }

    #[test]
    fn shared_sign_in_settings_never_reach_the_environment() {
        let f = Fixture::new("[claude]\n");
        let base = f.home.join(".claude");
        std::fs::create_dir_all(&base).unwrap();
        std::fs::write(
            base.join("settings.json"),
            r#"{"model":"opus","apiKeyHelper":"key.sh","env":{"ANTHROPIC_API_KEY":"shared"}}"#,
        )
        .unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        let text = std::fs::read_to_string(cfg_dir(&f).join("settings.json")).unwrap();
        assert!(
            text.contains("opus") && !text.contains("key.sh") && !text.contains("shared"),
            "{text}"
        );
    }

    #[test]
    fn bad_json_errors_name_the_file() {
        let f = Fixture::new("[claude]\n");
        let base = f.home.join(".claude");
        std::fs::create_dir_all(&base).unwrap();
        std::fs::write(base.join("settings.json"), "{nope").unwrap();
        let e = Claude.materialise(&f.ctx()).unwrap_err();
        assert!(
            e.message
                .contains(&base.join("settings.json").display().to_string()),
            "{}",
            e.message
        );
        std::fs::remove_file(base.join("settings.json")).unwrap();
        std::fs::write(f.home.join(".claude.json"), "{nope").unwrap();
        let e = Claude.materialise(&f.ctx()).unwrap_err();
        assert!(
            e.message
                .contains(&f.home.join(".claude.json").display().to_string())
                && e.message.contains("try again"),
            "{}",
            e.message
        );
    }

    #[test]
    fn changes_made_inside_the_environment_are_backed_up_before_regenerating() {
        let f = Fixture::new("[claude]\n");
        with_base(&f);
        Claude.materialise(&f.ctx()).unwrap();
        let dir = cfg_dir(&f);
        for file in ["settings.json", "CLAUDE.md"] {
            assert!(
                !dir.join(format!("{file}.bak")).exists(),
                "no backup on the first run"
            );
        }
        let generated = std::fs::read_to_string(dir.join("settings.json")).unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        assert!(
            !dir.join("settings.json.bak").exists(),
            "no backup when nothing changed"
        );

        std::fs::write(dir.join("settings.json"), r#"{"model":"haiku"}"#).unwrap();
        std::fs::write(dir.join("CLAUDE.md"), "# edited by Claude").unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        assert_eq!(
            std::fs::read_to_string(dir.join("settings.json.bak")).unwrap(),
            r#"{"model":"haiku"}"#
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("settings.json")).unwrap(),
            generated,
            "regenerated"
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("CLAUDE.md.bak")).unwrap(),
            "# edited by Claude"
        );
        assert!(
            std::fs::read_to_string(dir.join("CLAUDE.md"))
                .unwrap()
                .contains("# Base rules")
        );
    }

    #[test]
    fn no_backup_when_the_edit_matches_what_hydra_writes_next() {
        let f = Fixture::new("[claude]\n");
        with_base(&f);
        Claude.materialise(&f.ctx()).unwrap();
        let dir = cfg_dir(&f);
        std::fs::write(
            f.home.join(".claude").join("settings.json"),
            r#"{"model":"haiku"}"#,
        )
        .unwrap();
        let next = with_guard_hook(
            merge_settings(Some((Path::new("x"), r#"{"model":"haiku"}"#)), None, &[])
                .unwrap()
                .text,
        );
        std::fs::write(dir.join("settings.json"), &next).unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        assert!(!dir.join("settings.json.bak").exists());
    }

    #[test]
    fn backup_warning_names_both_places_for_lasting_changes() {
        let f = Fixture::new("[claude]\n");
        let l = layout(&f.ctx()).unwrap();
        std::fs::create_dir_all(&l.dir).unwrap();
        assert_eq!(
            write_generated(&l, "work", "settings.json", Some("{}\n")).unwrap(),
            None
        );
        std::fs::write(l.dir.join("settings.json"), "{\"x\":1}").unwrap();
        let warning = write_generated(&l, "work", "settings.json", Some("{}\n"))
            .unwrap()
            .unwrap();
        assert_eq!(
            warning,
            format!(
                "hydra: claude: settings.json was changed inside work; saved your version as {} - put lasting changes in {} or {}",
                l.dir.join("settings.json.bak").display(),
                l.base.join("settings.json").display(),
                l.over.join("settings.json").display()
            )
        );
    }

    #[test]
    fn claude_md_goes_away_when_the_base_one_is_deleted() {
        let f = Fixture::new("[claude]\n");
        with_base(&f);
        Claude.materialise(&f.ctx()).unwrap();
        assert!(cfg_dir(&f).join("CLAUDE.md").is_file());
        std::fs::remove_file(f.home.join(".claude").join("CLAUDE.md")).unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        assert!(!cfg_dir(&f).join("CLAUDE.md").exists());
        assert!(!cfg_dir(&f).join("CLAUDE.md.bak").exists());
    }

    #[test]
    fn real_folder_in_place_of_link_is_never_deleted() {
        let f = Fixture::new("[claude]\n");
        with_base(&f);
        let dir = cfg_dir(&f);
        std::fs::create_dir_all(dir.join("plugins")).unwrap();
        std::fs::write(dir.join("plugins").join("mine.json"), "x").unwrap();
        std::fs::create_dir_all(dir.join("skills")).unwrap(); // empty: replaced by the link
        let e = Claude.materialise(&f.ctx()).unwrap_err();
        assert!(
            e.message.contains("plugins") && e.message.contains("real folder"),
            "{}",
            e.message
        );
        let base_plugins = f.home.join(".claude").join("plugins");
        assert!(
            e.message.contains(&base_plugins.display().to_string()),
            "{}",
            e.message
        );
        let fix = e.fix.unwrap();
        assert!(
            fix.contains(&base_plugins.display().to_string()) && !fix.contains("~/.claude"),
            "{fix}"
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("plugins").join("mine.json")).unwrap(),
            "x"
        );
    }

    #[test]
    fn works_without_a_base() {
        let f = Fixture::new("[claude]\n");
        Claude.materialise(&f.ctx()).unwrap();
        let dir = cfg_dir(&f);
        assert!(dir.is_dir());
        assert_eq!(
            std::fs::read_to_string(dir.join("settings.json")).unwrap(),
            with_guard_hook("{}\n".to_string())
        );
        assert!(!dir.join("CLAUDE.md").exists());
    }

    #[test]
    fn claude_base_setting_moves_the_base() {
        let f = Fixture::new("[claude]\n");
        let alt = f.home.join("dotfiles").join("claude");
        std::fs::create_dir_all(alt.join("skills")).unwrap();
        std::fs::write(alt.join(".claude.json"), r#"{"mcpServers":{"alt":{}}}"#).unwrap();
        std::fs::create_dir_all(f.paths.root()).unwrap();
        let alt_toml = alt.to_string_lossy().replace('\\', "/");
        std::fs::write(
            f.paths.config_file(),
            format!("claude_base = \"{alt_toml}\"\n"),
        )
        .unwrap();
        Claude.materialise(&f.ctx()).unwrap();
        assert!(is_link(&cfg_dir(&f).join("skills")));
        assert!(
            std::fs::read_to_string(cfg_dir(&f).join(".claude.json"))
                .unwrap()
                .contains("\"alt\"")
        );
    }

    #[test]
    fn a_configured_claude_base_that_does_not_exist_is_an_error() {
        let f = Fixture::new("[claude]\n");
        let missing = f.home.join("no-such-folder");
        std::fs::create_dir_all(f.paths.root()).unwrap();
        std::fs::write(
            f.paths.config_file(),
            format!(
                "claude_base = \"{}\"\n",
                missing.to_string_lossy().replace('\\', "/")
            ),
        )
        .unwrap();
        let e = Claude.materialise(&f.ctx()).unwrap_err();
        assert!(
            e.message.starts_with("claude_base ") && e.message.ends_with(" doesn't exist"),
            "{}",
            e.message
        );
        assert_eq!(e.fix.as_deref(), Some("fix claude_base in config.toml"));
    }

    #[test]
    fn api_key_environments_need_no_sign_in() {
        for key in [
            "ANTHROPIC_API_KEY",
            "anthropic_auth_token",
            "CLAUDE_CODE_OAUTH_TOKEN",
        ] {
            let f = Fixture::new(&format!("[claude]\n[env]\n{key} = \"secret:work/k\"\n"));
            Claude.materialise(&f.ctx()).unwrap();
            assert_eq!(Claude.sign_in_hint(&f.ctx()), None, "{key}");
            let r = Claude.check(&f.ctx(), &FakeRunner::default());
            assert_eq!(
                (r.status, r.detail),
                (Status::Info, format!("uses {key} from [env]"))
            );
        }
    }

    #[test]
    fn sign_in_hint_and_identity_come_from_files() {
        let f = Fixture::new("[claude]\n");
        Claude.materialise(&f.ctx()).unwrap();
        assert_eq!(
            Claude.sign_in_hint(&f.ctx()).as_deref(),
            Some("not signed in - run claude auth login")
        );
        let r = Claude.check(&f.ctx(), &FakeRunner::default());
        assert_eq!(r.status, Status::Missing);

        let dir = cfg_dir(&f);
        std::fs::write(dir.join(".credentials.json"), "{}").unwrap();
        std::fs::write(
            dir.join(".claude.json"),
            r#"{"oauthAccount":{"emailAddress":"work@example.com","organizationName":"acme"}}"#,
        )
        .unwrap();
        assert_eq!(Claude.sign_in_hint(&f.ctx()), None);
        let r = Claude.check(&f.ctx(), &FakeRunner::default());
        assert_eq!(
            (r.status, r.detail.as_str()),
            (Status::Ok, "work@example.com (acme)")
        );
        assert_eq!(
            Claude.auth_command(&f.ctx()).unwrap(),
            vec!["claude", "auth", "login"]
        );
    }
}
