use serde_json::{Map, Value};

/// Objects merge key by key (recursively); anything else in `over` replaces `base`.
pub fn deep_merge(base: Value, over: Value) -> Value {
    match (base, over) {
        (Value::Object(mut b), Value::Object(o)) => {
            for (k, ov) in o {
                let merged = match b.remove(&k) {
                    Some(bv) => deep_merge(bv, ov),
                    None => ov,
                };
                b.insert(k, merged);
            }
            Value::Object(b)
        }
        (_, over) => over,
    }
}

/// Case-insensitive glob with `*` (any run) and `?` (one character).
pub fn glob_match(pattern: &str, name: &str) -> bool {
    fn go(p: &[char], n: &[char]) -> bool {
        match (p.first(), n.first()) {
            (None, None) => true,
            (Some('*'), _) => go(&p[1..], n) || (!n.is_empty() && go(p, &n[1..])),
            (Some('?'), Some(_)) => go(&p[1..], &n[1..]),
            (Some(a), Some(b)) if a.eq_ignore_ascii_case(b) => go(&p[1..], &n[1..]),
            _ => false,
        }
    }
    let p: Vec<char> = pattern.chars().collect();
    let n: Vec<char> = name.chars().collect();
    go(&p, &n)
}

pub fn drop_excluded(servers: &mut Map<String, Value>, exclude: &[String]) {
    servers.retain(|name, _| !exclude.iter().any(|pat| glob_match(pat, name)));
}

fn parse_object(text: &str, what: &str) -> Result<Value, String> {
    let v: Value =
        serde_json::from_str(text).map_err(|e| format!("{what} isn't valid JSON: {e}"))?;
    if v.is_object() {
        Ok(v)
    } else {
        Err(format!("{what} must be a JSON object"))
    }
}

/// Base settings merged with the environment's overrides, minus excluded MCP servers.
pub fn merge_settings(
    base: Option<&str>,
    over: Option<&str>,
    exclude: &[String],
) -> Result<String, String> {
    let mut merged = Value::Object(Map::new());
    if let Some(b) = base {
        merged = deep_merge(merged, parse_object(b, "your Claude settings.json")?);
    }
    if let Some(o) = over {
        merged = deep_merge(
            merged,
            parse_object(o, "the environment's claude/settings.json")?,
        );
    }
    if let Some(Value::Object(servers)) = merged.get_mut("mcpServers") {
        drop_excluded(servers, exclude);
    }
    let mut out = serde_json::to_string_pretty(&merged).map_err(|e| e.to_string())?;
    out.push('\n');
    Ok(out)
}

/// Base CLAUDE.md followed by the environment's own section. `None` when neither exists.
pub fn render_claude_md(env: &str, base: Option<&str>, over: Option<&str>) -> Option<String> {
    if base.is_none() && over.is_none() {
        return None;
    }
    let mut s = format!(
        "<!-- generated by hydra for environment \"{env}\" - edit ~/.claude/CLAUDE.md or ~/.hydra/envs/{env}/claude/CLAUDE.md instead -->\n"
    );
    if let Some(b) = base {
        s.push_str(b);
    }
    if let Some(o) = over {
        if base.is_some() {
            s.push_str("\n\n");
        }
        s.push_str(o);
    }
    Some(s)
}

/// Copies the base's `mcpServers` (minus exclusions) into the environment's
/// `.claude.json`, leaving every other key alone. `Ok(None)` means nothing to write.
pub fn sync_mcp(
    state_json: Option<&str>,
    base_global_json: Option<&str>,
    exclude: &[String],
) -> Result<Option<String>, String> {
    let mut servers = match base_global_json {
        Some(text) => match parse_object(text, "your ~/.claude.json")?.get("mcpServers") {
            Some(Value::Object(m)) => m.clone(),
            _ => Map::new(),
        },
        None => Map::new(),
    };
    drop_excluded(&mut servers, exclude);
    let mut state = match state_json {
        Some(text) => serde_json::from_str::<Value>(text)
            .ok()
            .filter(Value::is_object)
            .ok_or_else(|| "the environment's .claude.json isn't valid JSON (Claude may be writing it); try again".to_string())?,
        None if servers.is_empty() => return Ok(None),
        None => Value::Object(Map::new()),
    };
    let wanted = Value::Object(servers);
    if state.get("mcpServers") == Some(&wanted) {
        return Ok(None);
    }
    state
        .as_object_mut()
        .expect("checked object")
        .insert("mcpServers".to_string(), wanted);
    let mut out = serde_json::to_string_pretty(&state).map_err(|e| e.to_string())?;
    out.push('\n');
    Ok(Some(out))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn deep_merge_merges_objects_and_replaces_the_rest() {
        let base = json!({"a": {"x": 1, "y": [1, 2]}, "b": "keep", "c": 1});
        let over = json!({"a": {"y": [9], "z": true}, "c": 2});
        assert_eq!(
            deep_merge(base, over),
            json!({"a": {"x": 1, "y": [9], "z": true}, "b": "keep", "c": 2})
        );
    }

    #[test]
    fn glob_matching() {
        assert!(glob_match("acme*", "acme-brain"));
        assert!(glob_match("*brain", "ACME-BRAIN"), "case-insensitive");
        assert!(glob_match("dash", "dash"));
        assert!(glob_match("d?sh", "dash"));
        assert!(!glob_match("acme*", "codegraph"));
        assert!(!glob_match("dash", "dashboard"));
    }

    #[test]
    fn settings_merge_with_exclusions() {
        let base = r#"{"model":"opus","mcpServers":{"acme-x":{},"codegraph":{}},"permissions":{"allow":["Bash"]}}"#;
        let over = r#"{"model":"sonnet"}"#;
        let out = merge_settings(Some(base), Some(over), &["acme*".to_string()]).unwrap();
        let v: Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v["model"], "sonnet");
        assert_eq!(v["permissions"]["allow"][0], "Bash");
        assert!(v["mcpServers"].get("acme-x").is_none());
        assert!(v["mcpServers"].get("codegraph").is_some());
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn settings_merge_without_files_is_an_empty_object() {
        assert_eq!(merge_settings(None, None, &[]).unwrap(), "{}\n");
    }

    #[test]
    fn settings_merge_reports_bad_json() {
        let err = merge_settings(Some("{nope"), None, &[]).unwrap_err();
        assert!(err.contains("settings.json"), "{err}");
    }

    #[test]
    fn claude_md_concatenates_with_marker() {
        let out = render_claude_md("work", Some("# Base\n"), Some("# Work only\n")).unwrap();
        assert!(out.starts_with("<!-- generated by hydra for environment \"work\""));
        assert!(out.contains("# Base\n\n\n# Work only\n"));
        assert_eq!(render_claude_md("work", None, None), None);
        let only_base = render_claude_md("work", Some("# Base"), None).unwrap();
        assert!(only_base.ends_with("# Base"));
    }

    #[test]
    fn sync_touches_only_mcp_servers() {
        let state = r#"{"oauthAccount":{"emailAddress":"a@b.c"},"projects":{"E:/x":{"k":1}},"mcpServers":{"old":{}}}"#;
        let base = r#"{"mcpServers":{"codegraph":{"command":"cg"},"acme-brain":{}},"oauthAccount":{"emailAddress":"base@x"}}"#;
        let out = sync_mcp(Some(state), Some(base), &["acme*".to_string()])
            .unwrap()
            .unwrap();
        let v: Value = serde_json::from_str(&out).unwrap();
        assert_eq!(
            v["oauthAccount"]["emailAddress"], "a@b.c",
            "account never copied from base"
        );
        assert_eq!(v["projects"]["E:/x"]["k"], 1);
        assert_eq!(
            v["mcpServers"],
            serde_json::json!({"codegraph": {"command": "cg"}})
        );
    }

    #[test]
    fn sync_is_a_no_op_when_already_in_sync() {
        let state = r#"{"mcpServers":{"codegraph":{"command":"cg"}}}"#;
        let base = r#"{"mcpServers":{"codegraph":{"command":"cg"}}}"#;
        assert_eq!(sync_mcp(Some(state), Some(base), &[]).unwrap(), None);
    }

    #[test]
    fn sync_creates_state_file_when_missing() {
        let base = r#"{"mcpServers":{"dash":{}}}"#;
        let out = sync_mcp(None, Some(base), &[]).unwrap().unwrap();
        assert_eq!(
            serde_json::from_str::<Value>(&out).unwrap(),
            serde_json::json!({"mcpServers": {"dash": {}}})
        );
        assert_eq!(
            sync_mcp(None, None, &[]).unwrap(),
            None,
            "nothing to sync, nothing written"
        );
    }

    #[test]
    fn sync_refuses_unparseable_state_file() {
        let err = sync_mcp(Some("{\"half"), Some(r#"{"mcpServers":{}}"#), &[]).unwrap_err();
        assert!(err.contains("try again"), "{err}");
    }
}
