use std::path::Path;

use hydra_core::config::{EnvConfig, GitConfig};
use hydra_core::contribution::Contribution;
use hydra_core::name::EnvName;
use hydra_core::paths::expand_tilde;
use hydra_core::provider::{CommandRunner, Ctx, IdentityReport, Provider, ProviderError, Status};

use crate::report::report;

pub struct Git;

const MANAGED: &[&str] = &[
    "GIT_CONFIG_GLOBAL",
    "GIT_AUTHOR_NAME",
    "GIT_AUTHOR_EMAIL",
    "GIT_COMMITTER_NAME",
    "GIT_COMMITTER_EMAIL",
    "GIT_SSH_COMMAND",
    "GIT_SSH",
];

fn fwd(p: &Path) -> String {
    p.to_string_lossy().replace('\\', "/")
}

/// A git config value in double quotes, with `\` and `"` escaped.
fn quote(v: &str) -> String {
    format!("\"{}\"", v.replace('\\', "\\\\").replace('"', "\\\""))
}

/// The per-environment global gitconfig. It includes the user's own ~/.gitconfig first,
/// so everything below overrides it.
pub fn render_gitconfig(name: &EnvName, cfg: &GitConfig, user_home: &Path) -> String {
    let mut s = format!(
        "# generated by hydra for environment \"{name}\" - edit ~/.hydra/envs/{name}/env.toml instead\n"
    );
    s.push_str(&format!(
        "[include]\n\tpath = {}\n",
        quote(&fwd(&user_home.join(".gitconfig")))
    ));
    if cfg.name.is_some() || cfg.email.is_some() || cfg.signing_key.is_some() {
        s.push_str("[user]\n");
        if let Some(n) = &cfg.name {
            s.push_str(&format!("\tname = {}\n", quote(n)));
        }
        if let Some(e) = &cfg.email {
            s.push_str(&format!("\temail = {}\n", quote(e)));
        }
        if let Some(k) = &cfg.signing_key {
            s.push_str(&format!(
                "\tsigningkey = {}\n",
                quote(&fwd(&expand_tilde(k, user_home)))
            ));
        }
    }
    if cfg.signing_key.is_some() {
        s.push_str("[gpg]\n\tformat = ssh\n");
    }
    if let Some(k) = &cfg.ssh_key {
        let key = fwd(&expand_tilde(k, user_home)).replace('\'', "'\\''");
        s.push_str(&format!(
            "[core]\n\tsshCommand = {}\n",
            quote(&format!("ssh -i '{key}' -o IdentitiesOnly=yes"))
        ));
    }
    s.push_str(
        "[credential \"https://github.com\"]\n\thelper =\n\thelper = !gh auth git-credential\n",
    );
    s
}

impl Provider for Git {
    fn id(&self) -> &'static str {
        "git"
    }
    fn is_configured(&self, env: &EnvConfig) -> bool {
        env.git.is_some()
    }
    fn managed_vars(&self) -> &'static [&'static str] {
        MANAGED
    }

    fn materialise(&self, ctx: &Ctx) -> Result<(), ProviderError> {
        let Some(cfg) = &ctx.env.git else {
            return Err(ProviderError::new("[git] section missing"));
        };
        for (field, value) in [("ssh_key", &cfg.ssh_key), ("signing_key", &cfg.signing_key)] {
            if let Some(v) = value {
                let p = expand_tilde(v, ctx.user_home);
                if !p.is_file() {
                    return Err(
                        ProviderError::new(format!("{} not found", p.display())).with_fix(format!(
                            "create the key, or fix {field} in {}",
                            ctx.paths.env_file(ctx.name).display()
                        )),
                    );
                }
            }
        }
        let dir = ctx.provider_dir("git");
        std::fs::create_dir_all(&dir)?;
        std::fs::write(
            dir.join("gitconfig"),
            render_gitconfig(ctx.name, cfg, ctx.user_home),
        )?;
        Ok(())
    }

    fn contribute(&self, ctx: &Ctx) -> Result<Contribution, ProviderError> {
        let mut c = Contribution::new().path(
            "GIT_CONFIG_GLOBAL",
            &ctx.provider_dir("git").join("gitconfig"),
        );
        for v in MANAGED.iter().filter(|v| **v != "GIT_CONFIG_GLOBAL") {
            c = c.unset(v);
        }
        Ok(c)
    }

    fn check(&self, ctx: &Ctx, run: &dyn CommandRunner) -> IdentityReport {
        let expected = ctx.env.git.as_ref().and_then(|g| g.email.clone());
        match (
            run.output("git", &["config", "--global", "user.email"]),
            expected,
        ) {
            (Ok(actual), Some(exp)) if actual == exp => report("git", Status::Ok, actual),
            (Ok(actual), Some(exp)) => report(
                "git",
                Status::Mismatch,
                format!("uses {actual}, expected {exp}"),
            ),
            (Ok(actual), None) => report("git", Status::Info, actual),
            (Err(e), _) => report("git", Status::Missing, e),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::{FakeRunner, Fixture};
    use hydra_core::contribution::VarValue;

    fn cfg(toml_src: &str) -> GitConfig {
        toml::from_str(toml_src).unwrap()
    }

    #[test]
    fn renders_full_gitconfig() {
        let c = cfg(
            "name = \"David\"\nemail = \"work@example.com\"\nssh_key = \"~/.ssh/id_work\"\nsigning_key = \"~/.ssh/id_work.pub\"\n",
        );
        let out = render_gitconfig(
            &EnvName::parse("work").unwrap(),
            &c,
            Path::new("C:/Users/you"),
        );
        assert_eq!(
            out,
            "# generated by hydra for environment \"work\" - edit ~/.hydra/envs/work/env.toml instead\n\
             [include]\n\tpath = \"C:/Users/you/.gitconfig\"\n\
             [user]\n\tname = \"David\"\n\temail = \"work@example.com\"\n\tsigningkey = \"C:/Users/you/.ssh/id_work.pub\"\n\
             [gpg]\n\tformat = ssh\n\
             [core]\n\tsshCommand = \"ssh -i 'C:/Users/you/.ssh/id_work' -o IdentitiesOnly=yes\"\n\
             [credential \"https://github.com\"]\n\thelper =\n\thelper = !gh auth git-credential\n"
        );
    }

    #[test]
    fn gitconfig_quotes_paths_with_spaces() {
        let c = cfg("ssh_key = \"~/.ssh/id work\"\nname = \"Jane \\\"JD\\\" Doe\"\n");
        let out = render_gitconfig(
            &EnvName::parse("work").unwrap(),
            &c,
            Path::new("C:\\Users\\Jane Doe"),
        );
        assert!(
            out.contains("\tpath = \"C:/Users/Jane Doe/.gitconfig\"\n"),
            "{out}"
        );
        assert!(
            out.contains(
                "sshCommand = \"ssh -i 'C:/Users/Jane Doe/.ssh/id work' -o IdentitiesOnly=yes\""
            ),
            "{out}"
        );
        assert!(out.contains("\tname = \"Jane \\\"JD\\\" Doe\"\n"), "{out}");
    }

    #[test]
    fn materialise_requires_the_ssh_key() {
        let f = Fixture::new("[git]\nssh_key = \"~/.ssh/missing\"\n");
        let e = Git.materialise(&f.ctx()).unwrap_err();
        assert!(e.message.ends_with("missing not found"), "{}", e.message);
        assert!(
            e.fix
                .unwrap()
                .starts_with("create the key, or fix ssh_key in")
        );
    }

    #[test]
    fn materialise_writes_gitconfig_and_contributes_it() {
        let f = Fixture::new("[git]\nemail = \"a@b.c\"\n");
        Git.materialise(&f.ctx()).unwrap();
        let file = f.paths.state_dir(&f.name).join("git").join("gitconfig");
        assert!(
            std::fs::read_to_string(&file)
                .unwrap()
                .contains("email = \"a@b.c\"")
        );
        let c = Git.contribute(&f.ctx()).unwrap();
        assert_eq!(
            c.vars["GIT_CONFIG_GLOBAL"],
            VarValue::Literal(file.to_string_lossy().into_owned())
        );
        assert!(c.unset.contains("GIT_AUTHOR_EMAIL") && c.unset.contains("GIT_SSH_COMMAND"));
    }

    #[test]
    fn check_compares_email() {
        let f = Fixture::new("[git]\nemail = \"a@b.c\"\n");
        let ok = FakeRunner::default().with("git config --global user.email", Ok("a@b.c"));
        assert_eq!(Git.check(&f.ctx(), &ok).status, Status::Ok);
        let wrong = FakeRunner::default().with("git config --global user.email", Ok("x@y.z"));
        let r = Git.check(&f.ctx(), &wrong);
        assert_eq!(
            (r.status, r.detail.as_str()),
            (Status::Mismatch, "uses x@y.z, expected a@b.c")
        );
    }
}
