use std::path::Path;

use hydra_core::config::{EnvConfig, GitConfig};
use hydra_core::contribution::Contribution;
use hydra_core::name::EnvName;
use hydra_core::paths::expand_tilde;
use hydra_core::provider::{CommandRunner, Ctx, IdentityReport, Provider, ProviderError, Status};

use crate::report::report;

pub struct Git;

const MANAGED: &[&str] = &[
    "GIT_CONFIG_GLOBAL",
    "GIT_AUTHOR_NAME",
    "GIT_AUTHOR_EMAIL",
    "GIT_COMMITTER_NAME",
    "GIT_COMMITTER_EMAIL",
    "GIT_SSH_COMMAND",
    "GIT_SSH",
];

fn fwd(p: &Path) -> String {
    p.to_string_lossy().replace('\\', "/")
}

/// A git config value in double quotes, with `\` and `"` escaped.
fn quote(v: &str) -> String {
    format!("\"{}\"", v.replace('\\', "\\\\").replace('"', "\\\""))
}

/// Every client-side hook git runs in a normal workflow; each gets a wrapper so the repo's own
/// hook (or the user's global one) still runs when `core.hooksPath` points at hydra's folder.
pub const HOOKS: &[&str] = &[
    "applypatch-msg",
    "pre-applypatch",
    "post-applypatch",
    "pre-commit",
    "pre-merge-commit",
    "prepare-commit-msg",
    "commit-msg",
    "post-commit",
    "pre-rebase",
    "post-checkout",
    "post-merge",
    "pre-push",
    "post-rewrite",
    "pre-auto-gc",
    "push-to-checkout",
    "sendemail-validate",
];

/// The hooks that ask `hydra guard git` before chaining.
const GUARDED: &[&str] = &["pre-commit", "pre-push"];

/// A POSIX shell single-quoted string.
fn sh_quote(v: &str) -> String {
    format!("'{}'", v.replace('\'', r"'\''"))
}

/// The wrapper git runs for `hook`: the guard (for commit and push), then the hook it replaces.
/// `chain_dir` is the user's global hooks folder, or empty for the repo's own `.git/hooks`.
pub fn render_hook(name: &EnvName, hook: &str, hydra_exe: &str, chain_dir: &str) -> String {
    let mut s = format!(
        "#!/bin/sh\n# generated by hydra - git hook wrapper for environment \"{name}\"\nhook={hook}\n"
    );
    s.push_str(&format!("hydra_exe={}\n", sh_quote(hydra_exe)));
    s.push_str("[ -x \"$hydra_exe\" ] || hydra_exe=$(command -v hydra 2>/dev/null)\n");
    if GUARDED.contains(&hook) {
        s.push_str(
            "if [ -n \"$hydra_exe\" ]; then \"$hydra_exe\" guard git \"$hook\" \"$@\" </dev/null || exit $?; fi\n",
        );
    }
    s.push_str(&format!("chain_dir={}\n", sh_quote(chain_dir)));
    // Not `--git-path hooks`: with core.hooksPath set that names this folder, and the
    // wrapper would exec itself forever.
    s.push_str("[ -n \"$chain_dir\" ] || chain_dir=\"$(git rev-parse --git-common-dir)/hooks\"\n");
    s.push_str(
        "if [ -x \"$chain_dir/$hook\" ]; then exec \"$chain_dir/$hook\" \"$@\"; fi\nexit 0\n",
    );
    s
}

/// The user's own global `core.hooksPath` (from `<user_home>/.gitconfig`), with `/` separators.
/// Empty when it isn't set, the file is missing or git can't be run.
fn user_hooks_path(user_home: &Path) -> String {
    let out = std::process::Command::new("git")
        .arg("config")
        .arg("--file")
        .arg(user_home.join(".gitconfig"))
        .args(["--get", "core.hooksPath"])
        .stdin(std::process::Stdio::null())
        .output();
    match out {
        Ok(o) if o.status.success() => {
            let v = String::from_utf8_lossy(&o.stdout).trim().to_string();
            if v.is_empty() {
                v
            } else {
                fwd(&expand_tilde(&v, user_home))
            }
        }
        _ => String::new(),
    }
}

/// The per-environment global gitconfig. It includes the user's own ~/.gitconfig first,
/// so everything below overrides it. `core.hooksPath` points at hydra's hook wrappers.
pub fn render_gitconfig(
    name: &EnvName,
    cfg: &GitConfig,
    user_home: &Path,
    hooks_dir: &Path,
) -> String {
    let mut s = format!(
        "# generated by hydra for environment \"{name}\" - edit ~/.hydra/envs/{name}/env.toml instead\n"
    );
    s.push_str(&format!(
        "[include]\n\tpath = {}\n",
        quote(&fwd(&user_home.join(".gitconfig")))
    ));
    if cfg.name.is_some() || cfg.email.is_some() || cfg.signing_key.is_some() {
        s.push_str("[user]\n");
        if let Some(n) = &cfg.name {
            s.push_str(&format!("\tname = {}\n", quote(n)));
        }
        if let Some(e) = &cfg.email {
            s.push_str(&format!("\temail = {}\n", quote(e)));
        }
        if let Some(k) = &cfg.signing_key {
            s.push_str(&format!(
                "\tsigningkey = {}\n",
                quote(&fwd(&expand_tilde(k, user_home)))
            ));
        }
    }
    if cfg.signing_key.is_some() {
        s.push_str("[gpg]\n\tformat = ssh\n");
    }
    s.push_str("[core]\n");
    if let Some(k) = &cfg.ssh_key {
        let key = fwd(&expand_tilde(k, user_home)).replace('\'', "'\\''");
        s.push_str(&format!(
            "\tsshCommand = {}\n",
            quote(&format!("ssh -i '{key}' -o IdentitiesOnly=yes"))
        ));
    }
    s.push_str(&format!("\thooksPath = {}\n", quote(&fwd(hooks_dir))));
    // Git Credential Manager keeps HTTPS logins for every other host (GitLab, Azure DevOps,
    // ...) in the OS credential store; a per-environment namespace keeps them apart.
    s.push_str(&format!("[credential]\n\tnamespace = hydra-{name}\n"));
    s.push_str(
        "[credential \"https://github.com\"]\n\thelper =\n\thelper = !gh auth git-credential\n",
    );
    s
}

impl Provider for Git {
    fn id(&self) -> &'static str {
        "git"
    }
    fn is_configured(&self, env: &EnvConfig) -> bool {
        env.git.is_some()
    }
    fn managed_vars(&self) -> &'static [&'static str] {
        MANAGED
    }

    fn materialise(&self, ctx: &Ctx) -> Result<(), ProviderError> {
        let Some(cfg) = &ctx.env.git else {
            return Err(ProviderError::new("[git] section missing"));
        };
        for (field, value) in [("ssh_key", &cfg.ssh_key), ("signing_key", &cfg.signing_key)] {
            if let Some(v) = value {
                let p = expand_tilde(v, ctx.user_home);
                if !p.is_file() {
                    return Err(
                        ProviderError::new(format!("{} not found", p.display())).with_fix(format!(
                            "create the key, or fix {field} in {}",
                            ctx.paths.env_file(ctx.name).display()
                        )),
                    );
                }
            }
        }
        let dir = ctx.provider_dir("git");
        let hooks = dir.join("hooks");
        std::fs::create_dir_all(&hooks)?;
        let hydra_exe = std::env::current_exe().map(|p| fwd(&p)).unwrap_or_default();
        let chain_dir = user_hooks_path(ctx.user_home);
        for hook in HOOKS {
            std::fs::write(
                hooks.join(hook),
                render_hook(ctx.name, hook, &hydra_exe, &chain_dir),
            )?;
        }
        std::fs::write(
            dir.join("gitconfig"),
            render_gitconfig(ctx.name, cfg, ctx.user_home, &hooks),
        )?;
        Ok(())
    }

    fn contribute(&self, ctx: &Ctx) -> Result<Contribution, ProviderError> {
        let mut c = Contribution::new().path(
            "GIT_CONFIG_GLOBAL",
            &ctx.provider_dir("git").join("gitconfig"),
        );
        for v in MANAGED.iter().filter(|v| **v != "GIT_CONFIG_GLOBAL") {
            c = c.unset(v);
        }
        Ok(c)
    }

    fn check(&self, ctx: &Ctx, run: &dyn CommandRunner) -> IdentityReport {
        let expected = ctx.env.git.as_ref().and_then(|g| g.email.clone());
        match (
            run.output("git", &["config", "--global", "user.email"]),
            expected,
        ) {
            (Ok(actual), Some(exp)) if actual == exp => report("git", Status::Ok, actual),
            (Ok(actual), Some(exp)) => report(
                "git",
                Status::Mismatch,
                format!("uses {actual}, expected {exp}"),
            ),
            (Ok(actual), None) => report("git", Status::Info, actual),
            (Err(e), _) => report("git", Status::Missing, e),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::{FakeRunner, Fixture};
    use hydra_core::contribution::VarValue;

    fn cfg(toml_src: &str) -> GitConfig {
        toml::from_str(toml_src).unwrap()
    }

    #[test]
    fn renders_full_gitconfig() {
        let c = cfg(
            "name = \"David\"\nemail = \"work@example.com\"\nssh_key = \"~/.ssh/id_work\"\nsigning_key = \"~/.ssh/id_work.pub\"\n",
        );
        let out = render_gitconfig(
            &EnvName::parse("work").unwrap(),
            &c,
            Path::new("C:/Users/you"),
            Path::new("C:\\hydra\\state\\work\\git\\hooks"),
        );
        assert_eq!(
            out,
            "# generated by hydra for environment \"work\" - edit ~/.hydra/envs/work/env.toml instead\n\
             [include]\n\tpath = \"C:/Users/you/.gitconfig\"\n\
             [user]\n\tname = \"David\"\n\temail = \"work@example.com\"\n\tsigningkey = \"C:/Users/you/.ssh/id_work.pub\"\n\
             [gpg]\n\tformat = ssh\n\
             [core]\n\tsshCommand = \"ssh -i 'C:/Users/you/.ssh/id_work' -o IdentitiesOnly=yes\"\n\thooksPath = \"C:/hydra/state/work/git/hooks\"\n\
             [credential]\n\tnamespace = hydra-work\n\
             [credential \"https://github.com\"]\n\thelper =\n\thelper = !gh auth git-credential\n"
        );
    }

    #[test]
    fn credential_namespace_is_per_environment() {
        let out = render_gitconfig(
            &EnvName::parse("personal").unwrap(),
            &cfg(""),
            Path::new("C:/Users/you"),
            Path::new("C:/h"),
        );
        assert!(
            out.contains("[credential]\n\tnamespace = hydra-personal\n"),
            "{out}"
        );
    }

    #[test]
    fn gitconfig_quotes_paths_with_spaces() {
        let c = cfg("ssh_key = \"~/.ssh/id work\"\nname = \"Jane \\\"JD\\\" Doe\"\n");
        let out = render_gitconfig(
            &EnvName::parse("work").unwrap(),
            &c,
            Path::new("C:\\Users\\Jane Doe"),
            Path::new("C:/h"),
        );
        assert!(
            out.contains("\tpath = \"C:/Users/Jane Doe/.gitconfig\"\n"),
            "{out}"
        );
        assert!(
            out.contains(
                "sshCommand = \"ssh -i 'C:/Users/Jane Doe/.ssh/id work' -o IdentitiesOnly=yes\""
            ),
            "{out}"
        );
        assert!(out.contains("\tname = \"Jane \\\"JD\\\" Doe\"\n"), "{out}");
    }

    #[test]
    fn materialise_requires_the_ssh_key() {
        let f = Fixture::new("[git]\nssh_key = \"~/.ssh/missing\"\n");
        let e = Git.materialise(&f.ctx()).unwrap_err();
        assert!(e.message.ends_with("missing not found"), "{}", e.message);
        assert!(
            e.fix
                .unwrap()
                .starts_with("create the key, or fix ssh_key in")
        );
    }

    #[test]
    fn materialise_writes_gitconfig_and_contributes_it() {
        let f = Fixture::new("[git]\nemail = \"a@b.c\"\n");
        Git.materialise(&f.ctx()).unwrap();
        let file = f.paths.state_dir(&f.name).join("git").join("gitconfig");
        assert!(
            std::fs::read_to_string(&file)
                .unwrap()
                .contains("email = \"a@b.c\"")
        );
        let c = Git.contribute(&f.ctx()).unwrap();
        assert_eq!(
            c.vars["GIT_CONFIG_GLOBAL"],
            VarValue::Literal(file.to_string_lossy().into_owned())
        );
        assert!(c.unset.contains("GIT_AUTHOR_EMAIL") && c.unset.contains("GIT_SSH_COMMAND"));
    }

    const ALL_HOOKS: &[&str] = &[
        "applypatch-msg",
        "pre-applypatch",
        "post-applypatch",
        "pre-commit",
        "pre-merge-commit",
        "prepare-commit-msg",
        "commit-msg",
        "post-commit",
        "pre-rebase",
        "post-checkout",
        "post-merge",
        "pre-push",
        "post-rewrite",
        "pre-auto-gc",
        "push-to-checkout",
        "sendemail-validate",
    ];

    fn hooks_dir(f: &Fixture) -> std::path::PathBuf {
        f.paths.state_dir(&f.name).join("git").join("hooks")
    }

    #[test]
    fn materialise_points_core_hooks_path_at_the_wrappers() {
        let f = Fixture::new("[git]\nemail = \"a@b.c\"\n");
        Git.materialise(&f.ctx()).unwrap();
        let gitconfig =
            std::fs::read_to_string(f.paths.state_dir(&f.name).join("git").join("gitconfig"))
                .unwrap();
        let dir = hooks_dir(&f).to_string_lossy().replace('\\', "/");
        assert!(
            gitconfig.contains(&format!("[core]\n\thooksPath = \"{dir}\"\n")),
            "{gitconfig}"
        );
        for hook in ALL_HOOKS {
            assert!(hooks_dir(&f).join(hook).is_file(), "{hook} missing");
        }
    }

    #[test]
    fn hooks_path_joins_ssh_command_in_one_core_section() {
        let f = Fixture::new("[git]\nssh_key = \"~/.ssh/id\"\n");
        std::fs::create_dir_all(f.home.join(".ssh")).unwrap();
        std::fs::write(f.home.join(".ssh").join("id"), "k").unwrap();
        Git.materialise(&f.ctx()).unwrap();
        let gitconfig =
            std::fs::read_to_string(f.paths.state_dir(&f.name).join("git").join("gitconfig"))
                .unwrap();
        assert_eq!(gitconfig.matches("[core]").count(), 1, "{gitconfig}");
        assert!(
            gitconfig.contains("IdentitiesOnly=yes\"\n\thooksPath = "),
            "{gitconfig}"
        );
    }

    #[test]
    fn guarded_wrappers_call_hydra_and_chain() {
        let f = Fixture::new("[git]\nemail = \"a@b.c\"\n");
        Git.materialise(&f.ctx()).unwrap();
        let push = std::fs::read_to_string(hooks_dir(&f).join("pre-push")).unwrap();
        assert!(
            push.starts_with("#!/bin/sh\n# generated by hydra"),
            "{push}"
        );
        assert!(!push.contains('\r'), "{push:?}");
        assert!(push.contains("hook=pre-push\n"), "{push}");
        assert!(
            push.contains("guard git \"$hook\" \"$@\" </dev/null || exit $?"),
            "{push}"
        );
        assert!(push.contains("chain_dir=''\n"), "{push}");
        assert!(
            push.contains("chain_dir=\"$(git rev-parse --git-common-dir)/hooks\"\n"),
            "{push}"
        );
        assert!(
            push.contains("if [ -x \"$chain_dir/$hook\" ]; then exec \"$chain_dir/$hook\" \"$@\"; fi\nexit 0\n"),
            "{push}"
        );
        let commit = std::fs::read_to_string(hooks_dir(&f).join("pre-commit")).unwrap();
        assert!(commit.contains("guard git \"$hook\""), "{commit}");
        let msg = std::fs::read_to_string(hooks_dir(&f).join("commit-msg")).unwrap();
        assert!(!msg.contains("guard"), "{msg}");
        assert!(msg.contains("hook=commit-msg\n"), "{msg}");
    }

    #[test]
    fn wrappers_chain_to_the_users_global_hooks_path() {
        let f = Fixture::new("[git]\nemail = \"a@b.c\"\n");
        std::fs::write(
            f.home.join(".gitconfig"),
            "[core]\n\thooksPath = \"C:/my hooks/it's\"\n",
        )
        .unwrap();
        Git.materialise(&f.ctx()).unwrap();
        let commit = std::fs::read_to_string(hooks_dir(&f).join("pre-commit")).unwrap();
        assert!(
            commit.contains("chain_dir='C:/my hooks/it'\\''s'\n"),
            "{commit}"
        );
    }

    #[test]
    fn check_compares_email() {
        let f = Fixture::new("[git]\nemail = \"a@b.c\"\n");
        let ok = FakeRunner::default().with("git config --global user.email", Ok("a@b.c"));
        assert_eq!(Git.check(&f.ctx(), &ok).status, Status::Ok);
        let wrong = FakeRunner::default().with("git config --global user.email", Ok("x@y.z"));
        let r = Git.check(&f.ctx(), &wrong);
        assert_eq!(
            (r.status, r.detail.as_str()),
            (Status::Mismatch, "uses x@y.z, expected a@b.c")
        );
    }
}
