mod common;
use common::Home;
use predicates::prelude::*;

fn home() -> Home {
    let h = Home::new();
    h.write_env("work", "label = \"work\"\n");
    h.write_env("personal", "label = \"personal\"\n");
    h
}

fn config(h: &Home) -> String {
    std::fs::read_to_string(h.root().join("config.toml")).unwrap_or_default()
}

#[test]
fn bind_shows_lists_and_unbinds_a_folder_rule() {
    let h = home();
    let w = h.dir.path().join("w");
    let sub = w.join("sub");
    std::fs::create_dir_all(&sub).unwrap();

    h.hydra()
        .args(["bind"])
        .arg(&w)
        .arg("work")
        .assert()
        .success()
        .stdout(predicate::str::contains("bound"))
        .stdout(predicate::str::contains("-> work (rule"));
    assert!(config(&h).contains("work"), "{}", config(&h));

    h.hydra()
        .current_dir(&sub)
        .arg("bind")
        .assert()
        .success()
        .stdout(predicate::str::contains("-> work (rule"));

    h.hydra()
        .args(["bind", "--list"])
        .assert()
        .success()
        .stdout(predicate::str::contains("  ->  work"));

    h.hydra()
        .arg("unbind")
        .arg(&w)
        .assert()
        .success()
        .stdout(predicate::str::contains("removed rule"));
    assert!(!config(&h).contains("work"), "{}", config(&h));

    h.hydra()
        .arg("unbind")
        .arg(&w)
        .assert()
        .success()
        .stdout(predicate::str::contains("has no binding of its own"));

    h.hydra()
        .current_dir(&sub)
        .arg("bind")
        .assert()
        .success()
        .stdout(predicate::str::contains("isn't bound"));
}

#[test]
fn bind_with_one_argument_binds_the_current_folder() {
    let h = home();
    let w = h.dir.path().join("here");
    std::fs::create_dir_all(&w).unwrap();
    h.hydra()
        .current_dir(&w)
        .args(["bind", "personal"])
        .assert()
        .success()
        .stdout(predicate::str::contains("-> personal (rule"));
}

#[test]
fn bind_file_writes_a_hydra_file_and_unbind_removes_it() {
    let h = home();
    let c = h.dir.path().join("c");
    std::fs::create_dir_all(&c).unwrap();
    h.hydra()
        .args(["bind", "--file"])
        .arg(&c)
        .arg("personal")
        .assert()
        .success()
        .stdout(predicate::str::contains("env = \"personal\""));
    assert_eq!(
        std::fs::read_to_string(c.join(".hydra")).unwrap(),
        "# generated by hydra\nenv = \"personal\"\n"
    );
    h.hydra()
        .current_dir(&c)
        .arg("bind")
        .assert()
        .success()
        .stdout(predicate::str::contains("-> personal (.hydra in"));
    h.hydra().arg("unbind").arg(&c).assert().success();
    assert!(!c.join(".hydra").exists());
}

#[test]
fn bind_file_adds_to_git_exclude_in_a_repo() {
    let h = home();
    let repo = h.dir.path().join("repo");
    std::fs::create_dir_all(&repo).unwrap();
    assert!(
        std::process::Command::new("git")
            .args(["init", "-q"])
            .arg(&repo)
            .status()
            .unwrap()
            .success()
    );
    h.hydra()
        .args(["bind", "--file"])
        .arg(&repo)
        .arg("work")
        .assert()
        .success()
        .stdout(predicate::str::contains("added to .git/info/exclude"));
    let ex = std::fs::read_to_string(repo.join(".git/info/exclude")).unwrap();
    assert!(ex.lines().any(|l| l == ".hydra"), "{ex}");
}

#[test]
fn bind_warns_when_it_overrides_another_environment() {
    let h = home();
    let w = h.dir.path().join("w");
    std::fs::create_dir_all(&w).unwrap();
    h.hydra()
        .args(["bind"])
        .arg(&w)
        .arg("work")
        .assert()
        .success();
    h.hydra()
        .args(["bind"])
        .arg(&w)
        .arg("personal")
        .assert()
        .success()
        .stdout(predicate::str::contains("this rule overrides it"));
}

#[test]
fn bind_to_a_missing_environment_fails_and_writes_nothing() {
    let h = home();
    let x = h.dir.path().join("x");
    h.hydra()
        .args(["bind"])
        .arg(&x)
        .arg("nosuch")
        .assert()
        .failure()
        .stderr(predicate::str::contains("doesn't exist"));
    assert!(config(&h).is_empty());
}

#[test]
fn bind_with_too_many_arguments_fails() {
    let h = home();
    h.hydra().args(["bind", "a", "b", "c"]).assert().failure();
}

#[test]
fn bind_file_outside_a_repo_stops_at_the_ceiling_and_writes_no_exclude_file() {
    let h = home();
    let dir = h.dir.path().join("plain");
    std::fs::create_dir_all(&dir).unwrap();
    // Any repo above the temp folder (such as a home folder that is a repo) must stay untouched.
    let above: Vec<_> = h
        .dir
        .path()
        .ancestors()
        .skip(1)
        .map(|d| d.join(".git").join("info").join("exclude"))
        .map(|f| (std::fs::metadata(&f).ok().map(|m| m.len()), f))
        .collect();
    h.hydra()
        .args(["bind", "--file"])
        .arg(&dir)
        .arg("work")
        .assert()
        .success()
        .stdout(predicate::str::contains("added to").not());
    for (len, f) in above {
        assert_eq!(std::fs::metadata(&f).ok().map(|m| m.len()), len, "{f:?}");
    }
    assert!(!h.dir.path().join(".git").exists());
}

fn bound_folder(h: &Home, sub: &str, env: &str) -> std::path::PathBuf {
    let d = h.dir.path().join(sub);
    std::fs::create_dir_all(&d).unwrap();
    h.hydra().arg("bind").arg(&d).arg(env).assert().success();
    d
}

#[test]
fn shell_without_a_name_uses_the_folders_binding() {
    let h = home();
    let d = bound_folder(&h, "w", "work");
    h.hydra()
        .current_dir(&d)
        .args(["shell", "--shell", "pwsh"])
        .write_stdin("exit 0\n")
        .assert()
        .success()
        .stderr(predicate::str::contains("opening work (rule"));
}

#[test]
fn shell_without_a_name_in_an_unbound_folder_fails() {
    let h = home();
    let d = h.dir.path().join("plain");
    std::fs::create_dir_all(&d).unwrap();
    h.hydra()
        .current_dir(&d)
        .args(["shell", "--shell", "pwsh"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("isn't bound to an environment"))
        .stderr(predicate::str::contains("environments: personal, work"));
}

#[test]
fn env_new_home_writes_home_and_binds_it() {
    let h = home();
    let web = h.dir.path().join("web");
    h.hydra()
        .args(["env", "new", "web", "--home"])
        .arg(&web)
        .assert()
        .success()
        .stdout(predicate::str::contains("home"))
        .stdout(predicate::str::contains("-> web"));
    assert!(
        h.env_toml("web").contains("\nhome = \""),
        "{}",
        h.env_toml("web")
    );
    assert!(config(&h).contains("web"), "{}", config(&h));
}

#[test]
fn shell_with_a_name_from_elsewhere_starts_in_home() {
    let h = home();
    let web = h.dir.path().join("web");
    std::fs::create_dir_all(&web).unwrap();
    h.hydra()
        .args(["env", "new", "web", "--home"])
        .arg(&web)
        .assert()
        .success();
    let elsewhere = h.dir.path().join("elsewhere");
    std::fs::create_dir_all(&elsewhere).unwrap();
    let out = h
        .hydra()
        .current_dir(&elsewhere)
        .args(["shell", "web", "--shell", "pwsh"])
        .write_stdin("Write-Output \"[$PWD]\"; exit 0\n")
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let out = String::from_utf8_lossy(&out)
        .to_lowercase()
        .replace('\\', "/");
    let want = web.to_string_lossy().to_lowercase().replace('\\', "/");
    assert!(out.contains(&format!("[{want}]")), "{out}");
}

#[test]
fn whoami_reports_a_folder_mismatch() {
    let h = home();
    let d = bound_folder(&h, "p", "personal");
    h.hydra()
        .current_dir(&d)
        .args(["whoami", "--env", "work"])
        .assert()
        .failure()
        .stdout(predicate::str::contains("folder"))
        .stdout(predicate::str::contains("MISMATCH"));
}

#[test]
fn whoami_uses_the_folders_binding_and_says_when_unbound() {
    let h = home();
    let d = bound_folder(&h, "w", "work");
    h.hydra()
        .current_dir(&d)
        .arg("whoami")
        .assert()
        .success()
        .stdout(predicate::str::contains("-> work (rule"));
    let plain = h.dir.path().join("plain");
    std::fs::create_dir_all(&plain).unwrap();
    h.hydra()
        .current_dir(&plain)
        .args(["whoami", "--env", "work"])
        .assert()
        .success()
        .stdout(predicate::str::contains("isn't bound"));
}
