mod common;
use common::Home;
use predicates::prelude::*;

fn home() -> Home {
    let h = Home::new();
    h.write_env("work", "label = \"work\"\n");
    h.write_env("personal", "label = \"personal\"\n");
    h
}

fn config(h: &Home) -> String {
    std::fs::read_to_string(h.root().join("config.toml")).unwrap_or_default()
}

/// A hydra command whose git searches stop at the test folder, so `--file` never touches a repo
/// that happens to contain the machine's temp folder.
fn hydra(h: &Home) -> assert_cmd::Command {
    let mut c = h.hydra();
    c.env("GIT_CEILING_DIRECTORIES", h.dir.path());
    c
}

#[test]
fn bind_shows_lists_and_unbinds_a_folder_rule() {
    let h = home();
    let w = h.dir.path().join("w");
    let sub = w.join("sub");
    std::fs::create_dir_all(&sub).unwrap();

    hydra(&h)
        .args(["bind"])
        .arg(&w)
        .arg("work")
        .assert()
        .success()
        .stdout(predicate::str::contains("bound"))
        .stdout(predicate::str::contains("-> work (rule"));
    assert!(config(&h).contains("work"), "{}", config(&h));

    hydra(&h)
        .current_dir(&sub)
        .arg("bind")
        .assert()
        .success()
        .stdout(predicate::str::contains("-> work (rule"));

    hydra(&h)
        .args(["bind", "--list"])
        .assert()
        .success()
        .stdout(predicate::str::contains("  ->  work"));

    hydra(&h)
        .arg("unbind")
        .arg(&w)
        .assert()
        .success()
        .stdout(predicate::str::contains("removed rule"));
    assert!(!config(&h).contains("work"), "{}", config(&h));

    hydra(&h)
        .arg("unbind")
        .arg(&w)
        .assert()
        .success()
        .stdout(predicate::str::contains("has no binding of its own"));

    hydra(&h)
        .current_dir(&sub)
        .arg("bind")
        .assert()
        .success()
        .stdout(predicate::str::contains("isn't bound"));
}

#[test]
fn bind_with_one_argument_binds_the_current_folder() {
    let h = home();
    let w = h.dir.path().join("here");
    std::fs::create_dir_all(&w).unwrap();
    hydra(&h)
        .current_dir(&w)
        .args(["bind", "personal"])
        .assert()
        .success()
        .stdout(predicate::str::contains("-> personal (rule"));
}

#[test]
fn bind_file_writes_a_hydra_file_and_unbind_removes_it() {
    let h = home();
    let c = h.dir.path().join("c");
    std::fs::create_dir_all(&c).unwrap();
    hydra(&h)
        .args(["bind", "--file"])
        .arg(&c)
        .arg("personal")
        .assert()
        .success()
        .stdout(predicate::str::contains("env = \"personal\""));
    assert_eq!(
        std::fs::read_to_string(c.join(".hydra")).unwrap(),
        "# generated by hydra\nenv = \"personal\"\n"
    );
    hydra(&h)
        .current_dir(&c)
        .arg("bind")
        .assert()
        .success()
        .stdout(predicate::str::contains("-> personal (.hydra in"));
    hydra(&h).arg("unbind").arg(&c).assert().success();
    assert!(!c.join(".hydra").exists());
}

#[test]
fn bind_file_adds_to_git_exclude_in_a_repo() {
    let h = home();
    let repo = h.dir.path().join("repo");
    std::fs::create_dir_all(&repo).unwrap();
    assert!(
        std::process::Command::new("git")
            .args(["init", "-q"])
            .arg(&repo)
            .status()
            .unwrap()
            .success()
    );
    hydra(&h)
        .args(["bind", "--file"])
        .arg(&repo)
        .arg("work")
        .assert()
        .success()
        .stdout(predicate::str::contains("added to .git/info/exclude"));
    let ex = std::fs::read_to_string(repo.join(".git/info/exclude")).unwrap();
    assert!(ex.lines().any(|l| l == ".hydra"), "{ex}");
}

#[test]
fn bind_warns_when_it_overrides_another_environment() {
    let h = home();
    let w = h.dir.path().join("w");
    std::fs::create_dir_all(&w).unwrap();
    hydra(&h)
        .args(["bind"])
        .arg(&w)
        .arg("work")
        .assert()
        .success();
    hydra(&h)
        .args(["bind"])
        .arg(&w)
        .arg("personal")
        .assert()
        .success()
        .stdout(predicate::str::contains("this rule overrides it"));
}

#[test]
fn bind_to_a_missing_environment_fails_and_writes_nothing() {
    let h = home();
    let x = h.dir.path().join("x");
    hydra(&h)
        .args(["bind"])
        .arg(&x)
        .arg("nosuch")
        .assert()
        .failure()
        .stderr(predicate::str::contains("doesn't exist"));
    assert!(config(&h).is_empty());
}

#[test]
fn bind_with_too_many_arguments_fails() {
    let h = home();
    hydra(&h).args(["bind", "a", "b", "c"]).assert().failure();
}
