//! Edits that create and remove bindings: rules in `config.toml` (comment-preserving) and
//! `.hydra` files.
use std::io::Write;
use std::path::{Path, PathBuf};

use toml_edit::{DocumentMut, Item, Table, value};

fn parse(text: &str) -> Result<DocumentMut, String> {
    text.parse::<DocumentMut>().map_err(|e| e.to_string())
}

/// Inserts `[bindings]."<pattern>" = "<env>"`, or changes the env of an existing rule.
pub fn add_rule(config_text: &str, pattern: &str, env: &str) -> Result<String, String> {
    let mut doc = parse(config_text)?;
    if doc.get("bindings").is_none() {
        doc["bindings"] = Item::Table(Table::new());
    }
    let table = doc["bindings"]
        .as_table_like_mut()
        .ok_or("`bindings` in config.toml isn't a table")?;
    match table.get_mut(pattern) {
        // Assigning through the existing item keeps the rule's comments and position.
        Some(item) => *item = value(env),
        None => {
            table.insert(pattern, value(env));
        }
    }
    Ok(doc.to_string())
}

/// Removes a rule. The bool says whether it was there.
pub fn remove_rule(config_text: &str, pattern: &str) -> Result<(String, bool), String> {
    let mut doc = parse(config_text)?;
    let removed = match doc.get_mut("bindings").and_then(|b| b.as_table_like_mut()) {
        Some(table) => table.remove(pattern).is_some(),
        None => false,
    };
    Ok((doc.to_string(), removed))
}

/// The rule that binds a folder and everything under it: forward slashes, the user's case, `/**`.
pub fn rule_for_dir(dir: &Path) -> String {
    let s = dir.to_string_lossy().replace('\\', "/");
    format!("{}/**", s.trim_end_matches('/'))
}

/// True when the line assigns exactly this key (not a longer key such as `home_dir`).
fn is_key(trimmed: &str, key: &str) -> bool {
    trimmed
        .strip_prefix(key)
        .is_some_and(|r| r.trim_start().starts_with('='))
}

/// Adds `home = "<dir>"` (forward slashes) to an env.toml, right after its `color` line when it
/// has one. An existing active `home` is replaced.
pub fn set_home(env_text: &str, dir: &Path) -> Result<String, String> {
    let dir = dir.to_string_lossy().replace('\\', "/");
    let line = format!("home = {}", value(dir.as_str()));
    let mut out = Vec::new();
    let mut placed = false;
    let mut in_table = false;
    for l in env_text.lines() {
        let t = l.trim_start();
        if t.starts_with('[') {
            in_table = true;
        }
        if !in_table && is_key(t, "home") {
            if !placed {
                out.push(line.clone());
                placed = true;
            }
            continue;
        }
        out.push(l.to_string());
        if !placed && !in_table && is_key(t, "color") {
            out.push(line.clone());
            placed = true;
        }
    }
    if !placed {
        out.insert(0, line);
    }
    let text = format!("{}\n", out.join("\n"));
    parse(&text)?;
    Ok(text)
}

/// Writes `<dir>/.hydra` naming the environment.
pub fn write_hydra_file(dir: &Path, env: &str) -> std::io::Result<PathBuf> {
    let path = dir.join(".hydra");
    std::fs::write(&path, format!("# generated by hydra\nenv = \"{env}\"\n"))?;
    Ok(path)
}

/// Lists `.hydra` in the enclosing repo's `.git/info/exclude`. `Ok(true)` if it was added,
/// `Ok(false)` if it was already there, there is no repo, or the repo is a worktree (`.git` file).
/// Like git, the search for the repo stops below any folder in `GIT_CEILING_DIRECTORIES`.
pub fn exclude_in_git(dir: &Path) -> std::io::Result<bool> {
    let ceilings = std::env::var_os("GIT_CEILING_DIRECTORIES")
        .map(|v| std::env::split_paths(&v).collect::<Vec<_>>())
        .unwrap_or_default();
    exclude_in_git_below(dir, &ceilings)
}

fn same_folder(a: &Path, b: &Path) -> bool {
    crate::bindings::normalize(&a.to_string_lossy())
        == crate::bindings::normalize(&b.to_string_lossy())
}

fn exclude_in_git_below(dir: &Path, ceilings: &[PathBuf]) -> std::io::Result<bool> {
    let Some(git) = dir
        .ancestors()
        .take_while(|d| !ceilings.iter().any(|c| same_folder(c, d)))
        .map(|d| d.join(".git"))
        .find(|g| g.exists())
    else {
        return Ok(false);
    };
    if !git.is_dir() {
        return Ok(false);
    }
    let info = git.join("info");
    let file = info.join("exclude");
    let existing = std::fs::read_to_string(&file).unwrap_or_default();
    if existing.lines().any(|l| l.trim() == ".hydra") {
        return Ok(false);
    }
    std::fs::create_dir_all(&info)?;
    let mut f = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&file)?;
    if !existing.is_empty() && !existing.ends_with('\n') {
        f.write_all(b"\n")?;
    }
    f.write_all(b".hydra\n")?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    #[test]
    fn set_home_only_touches_the_top_level_home_key() {
        let d = Path::new("E:/n");
        let out = set_home(
            "color = \"#111111\"
home_dir = \"x\"
",
            d,
        )
        .unwrap();
        assert!(out.contains("home_dir = \"x\"") && out.contains("home = \"E:/n\""));
        let out = set_home(
            "color = \"#111111\"
[env]
home = \"y\"
",
            d,
        )
        .unwrap();
        assert!(
            out.contains(
                "[env]
home = \"y\""
            ),
            "{out}"
        );
        assert!(
            out.starts_with(
                "color = \"#111111\"
home = \"E:/n\"
"
            ),
            "{out}"
        );
        let out = set_home(
            "home = \"old\"
color = \"#111111\"
",
            d,
        )
        .unwrap();
        assert_eq!(
            out,
            "home = \"E:/n\"
color = \"#111111\"
"
        );
    }

    #[test]
    fn set_home_goes_after_color() {
        let t = "label = \"w\"\ncolor = \"#111111\"\n# home = \"E:/x\"\n[env]\n";
        let out = set_home(t, Path::new(r"E:\acme\web")).unwrap();
        assert_eq!(
            out,
            "label = \"w\"\ncolor = \"#111111\"\nhome = \"E:/acme/web\"\n# home = \"E:/x\"\n[env]\n"
        );
        let again = set_home(&out, Path::new("E:/b")).unwrap();
        assert_eq!(again.matches("\nhome =").count(), 1);
        assert!(again.contains("home = \"E:/b\""));
    }

    use super::*;

    #[test]
    fn adds_to_an_empty_bindings_table() {
        let out = add_rule("[bindings]\n", "E:/w/**", "work").unwrap();
        assert!(out.contains("\"E:/w/**\" = \"work\""), "{out}");
        let cfg: toml::Table = toml::from_str(&out).unwrap();
        assert_eq!(cfg["bindings"]["E:/w/**"].as_str(), Some("work"));
    }

    #[test]
    fn adds_when_there_is_no_bindings_table_and_keeps_comments() {
        let text = "# my config\ndefault_shell = \"bash\" # shell\n";
        let out = add_rule(text, "E:/w/**", "work").unwrap();
        assert!(out.contains("# my config"), "{out}");
        assert!(out.contains("# shell"), "{out}");
        let cfg: toml::Table = toml::from_str(&out).unwrap();
        assert_eq!(cfg["bindings"]["E:/w/**"].as_str(), Some("work"));
        assert_eq!(cfg["default_shell"].as_str(), Some("bash"));
    }

    #[test]
    fn replaces_an_existing_rules_env() {
        let text = "[bindings]\n# mine\n\"E:/w/**\" = \"old\"\n\"E:/x/**\" = \"x\"\n";
        let out = add_rule(text, "E:/w/**", "new").unwrap();
        assert!(out.contains("# mine"), "{out}");
        let cfg: toml::Table = toml::from_str(&out).unwrap();
        assert_eq!(cfg["bindings"]["E:/w/**"].as_str(), Some("new"));
        assert_eq!(cfg["bindings"]["E:/x/**"].as_str(), Some("x"));
    }

    #[test]
    fn removes_present_and_reports_absent() {
        let text = "[bindings]\n\"E:/w/**\" = \"work\"\n";
        let (out, removed) = remove_rule(text, "E:/w/**").unwrap();
        assert!(removed);
        assert!(!out.contains("E:/w"), "{out}");
        let (same, removed) = remove_rule(&out, "E:/w/**").unwrap();
        assert!(!removed);
        assert_eq!(same, out);
        assert!(!remove_rule("", "E:/w/**").unwrap().1);
    }

    #[test]
    fn rule_for_dir_keeps_case_and_uses_forward_slashes() {
        assert_eq!(rule_for_dir(Path::new(r"E:\Work\Repo")), "E:/Work/Repo/**");
        assert_eq!(rule_for_dir(Path::new(r"E:\Work\Repo\")), "E:/Work/Repo/**");
    }

    #[test]
    fn writes_a_hydra_file() {
        let d = tempfile::tempdir().unwrap();
        let p = write_hydra_file(d.path(), "work").unwrap();
        assert_eq!(p, d.path().join(".hydra"));
        assert_eq!(
            std::fs::read_to_string(p).unwrap(),
            "# generated by hydra\nenv = \"work\"\n"
        );
    }

    fn git_init(dir: &Path) {
        let ok = std::process::Command::new("git")
            .args(["init", "-q"])
            .arg(dir)
            .status()
            .unwrap()
            .success();
        assert!(ok);
    }

    #[test]
    fn excludes_hydra_once_in_a_repo() {
        let d = tempfile::tempdir().unwrap();
        git_init(d.path());
        let sub = d.path().join("a");
        std::fs::create_dir_all(&sub).unwrap();
        assert!(exclude_in_git(&sub).unwrap());
        assert!(!exclude_in_git(&sub).unwrap());
        let text = std::fs::read_to_string(d.path().join(".git/info/exclude")).unwrap();
        assert_eq!(text.lines().filter(|l| l.trim() == ".hydra").count(), 1);
    }

    #[test]
    fn exclude_outside_a_repo_is_false() {
        let d = tempfile::tempdir().unwrap();
        // Stop the search at the temp folder, in case the machine's temp area is inside a repo.
        let ceiling = d.path().to_path_buf();
        let inside = d.path().join("x");
        std::fs::create_dir_all(&inside).unwrap();
        assert!(!exclude_in_git_below(&inside, &[ceiling]).unwrap());
    }

    #[test]
    fn a_git_file_worktree_is_skipped() {
        let d = tempfile::tempdir().unwrap();
        std::fs::write(d.path().join(".git"), "gitdir: elsewhere\n").unwrap();
        assert!(!exclude_in_git(d.path()).unwrap());
    }
}
